let chapterSummaries: [String: [String: String]] = [
    "Genesis": [
        "1": "Creation",
        "2": "Eden and Humanity",
        "3": "The Fall",
        "4": "Cain and Abel",
        "5": "Genealogy from Adam to Noah",
        "6": "Wickedness and the Flood",
        "7": "The Flood Begins",
        "8": "The Flood Recedes",
        "9": "God's Covenant with Noah",
        "11": "Tower of Babel",
        "12": "Call of Abram",
        "13": "Abram and Lot Separate",
        "15": "God's Covenant with Abram",
        "17": "Covenant of Circumcision",
        "18": "Visitors and Promise of Isaac",
        "19": "Destruction of Sodom and Gomorrah",
        "21": "Birth of Isaac",
        "22": "Abraham Tested",
        "25": "Esau and Jacob",
        "28": "Jacob's Dream",
        "32": "Jacob Wrestles with God",
        "37": "Joseph's Dreams",
        "39": "Joseph in Egypt",
        "41": "Joseph Interprets Dreams",
        "42": "Brothers Go to Egypt",
        "45": "Joseph Reveals Himself",
        "50": "Death of Joseph",
    ],
    "Exodus": [
        "1": "Israelites in Egypt",
        "2": "Birth of Moses",
        "3": "The Burning Bush",
        "4": "Signs for Moses",
        "5": "Moses and Aaron Before Pharaoh",
        "6": "God's Promise of Deliverance",
        "7": "The First Plague",
        "8": "Plagues of Frogs, Gnats, and Flies",
        "9": "Plagues on Livestock, Boils, Hail",
        "10": "Plagues of Locusts and Darkness",
        "11": "The Final Plague Announced",
        "12": "The Passover and Exodus",
        "13": "Consecration of the Firstborn",
        "14": "Crossing the Red Sea",
        "15": "Song of Moses and Miriam",
        "16": "Manna and Quail Provided",
        "17": "Water from the Rock",
        "19": "At Mount Sinai",
        "20": "The Ten Commandments",
        "24": "Covenant Confirmed",
        "32": "The Golden Calf",
        "33": "Moses and God's Presence",
        "34": "New Tablets and Covenant Renewal",
        "40": "The Tabernacle Completed",
    ],
    "Leviticus": [
        "1": "Burnt Offerings",
        "2": "Grain Offerings",
        "3": "Fellowship Offerings",
        "4": "Sin Offerings",
        "5": "Additional Sin Offerings",
        "6": "Further Instructions",
        "7": "Regulations for Offerings",
        "8": "Ordination of Priests",
        "9": "Priestly Ministry Begins",
        "10": "Nadab and Abihu",
        "11": "Clean and Unclean Animals",
        "12": "Purification After Childbirth",
        "13": "Regulations About Skin Diseases",
        "14": "Cleansing from Skin Diseases",
        "15": "Bodily Discharges",
        "16": "Day of Atonement",
        "17": "Prohibition of Sacrifices Outside the Tabernacle",
        "18": "Unlawful Sexual Relations",
        "19": "Various Laws",
        "20": "Punishments for Sin",
        "21": "Rules for Priests",
        "22": "Acceptable Offerings",
        "23": "Appointed Festivals",
        "24": "The Lampstand and Bread",
        "25": "The Sabbath Year and Jubilee",
        "26": "Blessings and Curses",
        "27": "Redeeming What Is the Lord's",
    ],
    "Numbers": [
        "1": "The First Census",
        "2": "Arrangement of the Camp",
        "3": "Levites Assigned",
        "4": "Duties of Levite Clans",
        "5": "Purity in the Camp",
        "6": "Nazirite Vow",
        "7": "Offerings at Tabernacle Dedication",
        "8": "Setting Up the Lamps and Levites",
        "9": "Passover and the Cloud",
        "10": "Silver Trumpets and Departure",
        "11": "Complaints and Provision",
        "12": "Miriam and Aaron Oppose Moses",
        "13": "Spies Sent to Canaan",
        "14": "Rebellion and Punishment",
        "16": "Korah's Rebellion",
        "17": "Aaron's Staff Buds",
        "20": "Water from the Rock",
        "21": "The Bronze Serpent",
        "25": "Baal Worship at Peor",
        "26": "Second Census",
        "27": "Zelophehad's Daughters and Joshua",
        "31": "Vengeance on Midian",
        "32": "Settling East of the Jordan",
        "33": "Stages of Israel's Journey",
        "34": "Boundaries of Canaan",
        "35": "Cities for Levites and Refuge",
        "36": "Inheritance and Marriage Laws",
    ],
    "Deuteronomy": [
        "1": "Moses Reviews Israel's Journey",
        "2": "Wilderness Wanderings",
        "3": "Victories Over Kings",
        "4": "Obedience Commanded",
        "5": "The Ten Commandments Reiterated",
        "6": "Love the Lord",
        "7": "Driving Out Nations",
        "8": "Remember the Lord",
        "9": "Not Because of Righteousness",
        "10": "Tablets Replaced",
        "11": "Love and Obey",
        "12": "One Place of Worship",
        "13": "Avoiding Idolatry",
        "14": "Clean and Unclean",
        "15": "The Sabbath Year",
        "16": "Annual Festivals",
        "17": "Legal Decisions and Kingship",
        "18": "Priests, Levites, and Prophets",
        "19": "Cities of Refuge",
        "20": "Warfare Laws",
        "21": "Various Laws",
        "22": "Miscellaneous Laws",
        "23": "Exclusions from the Assembly",
        "24": "Additional Laws",
        "25": "Fairness and Justice",
        "26": "Firstfruits and Tithes",
        "27": "Curses from Mount Ebal",
        "28": "Blessings and Curses",
        "29": "Covenant Renewal",
        "30": "Prosperity After Turning to God",
        "31": "Joshua Commissioned",
        "32": "The Song of Moses",
        "33": "Moses Blesses the Tribes",
        "34": "Death of Moses",
    ],
    "Joshua": [
        "1": "Joshua Takes Command",
        "2": "Rahab and the Spies",
        "3": "Crossing the Jordan",
        "4": "Memorial Stones",
        "5": "Circumcision and Passover at Gilgal",
        "6": "The Fall of Jericho",
        "7": "Achan's Sin",
        "8": "Conquest of Ai",
        "9": "The Gibeonite Deception",
        "10": "Sun Stands Still",
        "11": "Northern Conquests",
        "12": "List of Defeated Kings",
        "13": "Land Yet to Be Conquered",
        "14": "Caleb's Inheritance",
        "15": "Allotment for Judah",
        "18": "Remaining Land Divided",
        "19": "Allotments for Remaining Tribes",
        "20": "Cities of Refuge",
        "21": "Towns for the Levites",
        "22": "Eastern Tribes Return Home",
        "23": "Joshua's Farewell to Leaders",
        "24": "Covenant Renewed at Shechem",
    ],
    "Judges": [
        "1": "Continuing Conquest",
        "2": "Israel's Disobedience",
        "3": "First Judges",
        "4": "Deborah and Barak",
        "5": "Song of Deborah",
        "6": "Gideon Called",
        "7": "Gideon's 300 Men",
        "8": "Gideon's Victory and Downfall",
        "9": "Abimelech's Rise and Fall",
        "10": "Tola and Jair",
        "11": "Jephthah's Vow",
        "12": "Jephthah and Subsequent Judges",
        "13": "Birth of Samson",
        "14": "Samson's Marriage",
        "15": "Samson's Revenge",
        "16": "Samson and Delilah",
        "17": "Micah's Idols",
        "18": "Danites Take Micah's Idols",
        "19": "The Levite's Concubine",
        "20": "War Against Benjamin",
        "21": "Wives for the Benjamites",
    ],
    "Ruth": [
        "1": "Ruth's Loyalty to Naomi",
        "2": "Ruth Meets Boaz",
        "3": "Ruth at the Threshing Floor",
        "4": "Boaz Redeems Ruth",
    ],
    "1 Samuel": [
        "1": "Birth of Samuel",
        "2": "Hannah's Prayer and Eli's Wicked Sons",
        "3": "The Lord Calls Samuel",
        "4": "The Ark Captured by Philistines",
        "5": "The Ark in Philistine Territory",
        "6": "Return of the Ark",
        "7": "Samuel Leads Israel",
        "8": "Israel Demands a King",
        "9": "Saul Chosen as King",
        "10": "Saul Anointed and Proclaimed King",
        "11": "Saul Defeats the Ammonites",
        "12": "Samuel's Farewell Speech",
        "13": "Saul's Unlawful Sacrifice",
        "14": "Jonathan's Victory",
        "15": "Saul Rejected as King",
        "16": "David Anointed",
        "17": "David and Goliath",
        "18": "Saul's Jealousy",
        "19": "David Flees Saul",
        "20": "David and Jonathan's Covenant",
        "21": "David at Nob and Gath",
        "22": "Saul Kills the Priests of Nob",
        "23": "David Saves Keilah",
        "24": "David Spares Saul",
        "25": "Death of Samuel and Nabal's Story",
        "26": "David Spares Saul Again",
        "27": "David Among the Philistines",
        "28": "Saul Consults a Medium",
        "29": "Philistines Reject David",
        "30": "David Retrieves Plunder",
        "31": "Death of Saul and His Sons",
    ],
    "2 Samuel": [
        "1": "David Hears of Saul's Death",
        "2": "David Anointed King over Judah",
        "3": "Abner Joins David",
        "4": "Ish-Bosheth's Death",
        "5": "David Becomes King over All Israel",
        "6": "The Ark Brought to Jerusalem",
        "7": "God's Covenant with David",
        "8": "David's Victories",
        "9": "David and Mephibosheth",
        "10": "War with the Ammonites and Arameans",
        "11": "David and Bathsheba",
        "12": "Nathan Confronts David",
        "13": "Amnon and Tamar",
        "14": "Absalom's Return",
        "15": "Absalom's Conspiracy",
        "16": "David and Ziba; Shimei Curses David",
        "17": "Ahithophel and Hushai's Counsel",
        "18": "Absalom's Death",
        "19": "David Restored as King",
        "20": "Sheba's Rebellion",
        "21": "Famine and Battles",
        "22": "David's Song of Praise",
        "23": "David's Last Words and Mighty Men",
        "24": "David's Census and the Plague",
    ],
    "1 Kings": [
        "1": "Adonijah Sets Himself Up as King",
        "2": "David's Charge to Solomon and Death",
        "3": "Solomon's Wisdom",
        "4": "Solomon's Officials and Prosperity",
        "5": "Preparations for Building the Temple",
        "6": "Building the Temple",
        "7": "Solomon Builds His Palace",
        "8": "Ark Brought to the Temple",
        "9": "God's Promise and Warnings",
        "10": "Queen of Sheba Visits",
        "11": "Solomon's Wives and Idolatry",
        "12": "The Kingdom Divided",
        "13": "The Man of God from Judah",
        "14": "Prophecies Against Jeroboam and Rehoboam",
        "15": "Kings of Judah and Israel",
        "16": "Further Kings of Israel",
        "17": "Elijah Predicts Drought",
        "18": "Elijah on Mount Carmel",
        "19": "Elijah Flees to Horeb",
        "20": "Ahab Defeats Ben-Hadad",
        "21": "Naboth's Vineyard",
        "22": "Ahab's Death",
    ],
    "2 Kings": [
        "1": "Elijah and King Ahaziah",
        "2": "Elijah Taken Up to Heaven",
        "3": "Moab Revolts Against Israel",
        "4": "Elisha's Miracles",
        "5": "Naaman Healed of Leprosy",
        "6": "Floating Axe Head and Aramean Attack",
        "7": "Siege Lifted",
        "8": "The Shunammite's Land Restored",
        "9": "Jehu Anointed King of Israel",
        "10": "Jehu's Reign",
        "11": "Athaliah and Joash",
        "12": "Joash Repairs the Temple",
        "13": "Jehoahaz and Jehoash of Israel",
        "14": "Amaziah and Jeroboam II",
        "15": "Uzziah, Jotham, and Other Kings",
        "16": "Ahaz King of Judah",
        "17": "Fall of Israel",
        "18": "Hezekiah's Reforms",
        "19": "Isaiah's Prophecy",
        "20": "Hezekiah's Illness and Recovery",
        "21": "Manasseh and Amon",
        "22": "Josiah's Reforms Begin",
        "23": "Josiah's Reforms and Death",
        "24": "Judah's Decline",
        "25": "Fall of Jerusalem",
    ],
    "1 Chronicles": [
        "10": "Death of Saul",
        "11": "David Becomes King",
        "12": "Warriors Join David",
        "13": "The Ark Brought to Kiriath Jearim",
        "14": "David's Family and Victories",
        "15": "The Ark Brought to Jerusalem",
        "16": "David's Psalm of Thanks",
        "17": "God's Covenant with David",
        "18": "David's Victories",
        "19": "Defeat of the Ammonites and Arameans",
        "20": "Capture of Rabbah",
        "21": "David's Census and the Plague",
        "22": "Preparations for the Temple",
        "23": "Organization of the Levites",
        "24": "Divisions of Priests",
        "25": "Musicians for the Temple",
        "26": "Gatekeepers and Treasurers",
        "27": "Military and Civil Officials",
        "28": "David's Charge to Israel and Solomon",
        "29": "Offerings for the Temple and David's Death",
    ],
    "2 Chronicles": [
        "1": "Solomon's Wisdom and Wealth",
        "2": "Preparations for Building the Temple",
        "3": "Building the Temple",
        "4": "The Temple's Furnishings",
        "5": "The Ark Brought to the Temple",
        "6": "Solomon's Prayer of Dedication",
        "7": "The Lord Appears to Solomon",
        "8": "Solomon's Achievements",
        "9": "The Queen of Sheba and Solomon's Wealth",
        "10": "Rehoboam and the Division of the Kingdom",
        "11": "Rehoboam Fortifies Judah",
        "12": "Egypt Attacks Jerusalem",
        "13": "Abijah King of Judah",
        "14": "Asa's Reforms",
        "15": "Asa's Religious Reforms",
        "16": "Asa's Later Years",
        "17": "Jehoshaphat Succeeds Asa",
        "18": "Ahab and Jehoshaphat",
        "19": "Jehoshaphat's Reforms",
        "20": "Jehoshaphat Defeats Moab and Ammon",
        "21": "Jehoram King of Judah",
        "22": "Ahaziah and Athaliah",
        "23": "Joash Becomes King",
        "24": "Joash Repairs the Temple",
        "25": "Amaziah King of Judah",
        "26": "Uzziah King of Judah",
        "27": "Jotham King of Judah",
        "28": "Ahaz King of Judah",
        "29": "Hezekiah Purifies the Temple",
        "30": "Hezekiah Celebrates the Passover",
        "31": "Hezekiah's Further Reforms",
        "32": "Sennacherib Threatens Jerusalem",
        "33": "Manasseh and Amon",
        "34": "Josiah's Reforms",
        "35": "Josiah Celebrates the Passover",
        "36": "The Fall of Jerusalem",
    ],
    "Ezra": [
        "1": "Cyrus's Decree to Rebuild the Temple",
        "2": "The Exiles Who Returned",
        "3": "Rebuilding the Altar and Laying the Foundation",
        "4": "Opposition to Rebuilding the Temple",
        "5": "Resuming the Temple Construction",
        "6": "Completion and Dedication of the Temple",
        "7": "Ezra Sent to Teach the People",
        "8": "Ezra's Return to Jerusalem",
        "9": "Intermarriage with Pagans",
        "10": "Repentance and Reform",
    ],
    "Nehemiah": [
        "1": "Nehemiah's Prayer",
        "2": "Nehemiah Sent to Jerusalem",
        "3": "Rebuilding the Wall",
        "4": "Opposition to the Work",
        "5": "Nehemiah's Reforms",
        "6": "Plot to Harm Nehemiah",
        "7": "List of the Exiles Who Returned",
        "8": "Ezra Reads the Law",
        "9": "Confession and Worship",
        "10": "The People’s Pledge",
        "11": "The New Residents of Jerusalem",
        "12": "Dedication of the Wall",
        "13": "Nehemiah’s Final Reforms",
    ],
    "Esther": [
        "1": "Queen Vashti Deposed",
        "2": "Esther Becomes Queen",
        "3": "Haman's Plot Against the Jews",
        "4": "Mordecai Persuades Esther to Help",
        "5": "Esther's Request to the King",
        "6": "The King Honors Mordecai",
        "7": "Haman Hanged",
        "8": "The King’s Edict in Behalf of the Jews",
        "9": "The Triumph of the Jews",
        "10": "The Greatness of Mordecai",
    ],
    "Job": [
        "1": "Job's Character and Wealth; First Test",
        "2": "Second Test and Job's Friends",
        "3": "Job Laments His Birth",
        "8": "Bildad's First Speech",
        "11": "Zophar's First Speech",
        "15": "Eliphaz's Second Speech",
        "18": "Bildad's Second Speech",
        "19": "Job's Reply to Bildad",
        "20": "Zophar's Second Speech",
        "21": "Job's Reply to Zophar",
        "22": "Eliphaz's Third Speech",
        "25": "Bildad's Third Speech",
        "32": "Elihu's Speeches Begin",
        "42": "Job's Restoration",
    ],
    "Psalms": [
        "1": "Book 1",
        "42": "Book 2",
        "73": "Book 3",
        "90": "Book 4",
        "107": "Book 5",
    ],
    "Proverbs": [
        "1": "The Beginning of Knowledge",
        "2": "The Value of Wisdom",
        "3": "Trust in the Lord with All Your Heart",
        "4": "A Father's Wise Instruction",
        "5": "Warning Against Adultery",
        "6": "Warnings Against Folly",
        "7": "The Allure of the Adulterous Woman",
        "8": "The Blessings of Wisdom",
        "9": "The Way of Wisdom and the Way of Folly",
        "10": "Proverbs of Solomon",
        "11": "The Righteous and the Wicked",
        "12": "The Way of the Righteous",
        "13": "Wisdom for Life",
        "14": "The Upright and the Wicked",
        "15": "A Gentle Answer Turns Away Wrath",
        "16": "Commit Your Work to the Lord",
        "17": "Wisdom in Relationships",
        "18": "Wisdom in Speech",
        "19": "Wisdom in Conduct",
        "20": "Wisdom in Deeds",
        "21": "Wisdom and Justice",
        "22": "A Good Name and Humility",
        "23": "Wisdom in Life Choices",
        "24": "Wisdom and Justice",
        "25": "More Proverbs of Solomon",
        "26": "Fools and Their Folly",
        "27": "Wisdom in Relationships",
        "28": "Wisdom in Leadership",
        "29": "Wisdom and Discipline",
        "30": "Sayings of Agur",
        "31": "Sayings of King Lemuel and the Wife of Noble Character",
    ],
    "Ecclesiastes": [
        "1": "The Vanity of Life",
        "2": "The Futility of Pleasure and Work",
        "3": "A Time for Everything",
        "4": "The Vanity of Selfish Toil",
        "5": "Reverence for God",
        "6": "The Vanity of Wealth and Honor",
        "7": "The Value of Wisdom",
        "8": "Obeying Authorities",
        "9": "Enjoy Life Despite Its Uncertainties",
        "10": "Wisdom and Folly",
        "11": "The Uncertainty of Life",
        "12": "Remember Your Creator",
    ],
    "Song of Solomon": [
        "1": "The Bride's Love for the King",
        "2": "The Bride's Delight in Her Beloved",
        "3": "The Bride's Dream",
        "4": "The Beauty of the Bride",
        "5": "The Bride's Troubled Dream",
        "6": "The Beauty of the Bride Renewed",
        "7": "Expressions of Mutual Delight",
        "8": "Longing for Love and Climax of Union",
    ],
    "Isaiah": [
        "1": "Judah’s Rebellion and Call to Repentance",
        "2": "The Mountain of the Lord",
        "3": "Judgment on Judah and Jerusalem",
        "4": "The Branch of the Lord",
        "5": "The Vineyard of the Lord",
        "6": "Isaiah's Commission",
        "7": "The Sign of Immanuel",
        "8": "Assyria Will Invade the Land",
        "9": "The Coming of the Prince of Peace",
        "10": "Woe to Assyria",
        "11": "The Branch from Jesse",
        "12": "Songs of Praise",
        "24": "The Lord's Devastation of the Earth",
        "25": "Praise to the Lord",
        "26": "A Song of Trust",
        "27": "Deliverance of Israel",
    ],
    "Jeremiah": [
        "1": "Jeremiah's Call and Commission",
        "2": "Israel Forsakes God",
        "3": "Unfaithful Israel",
        "4": "Disaster from the North",
        "5": "Israel's Unfaithfulness",
        "6": "The Siege of Jerusalem",
        "7": "False Religion Worthless",
        "8": "Sin and Punishment",
        "9": "Jeremiah's Lament",
        "10": "Idolatry and the True God",
        "11": "The Covenant is Broken",
        "12": "Jeremiah's Complaint",
        "13": "The Linen Belt",
        "14": "Drought, Famine, and Sword",
        "15": "God's Inevitable Judgment",
        "16": "Jeremiah's Life as a Sign",
        "17": "The Sin of Judah",
        "18": "The Potter and the Clay",
        "19": "The Broken Jar",
        "20": "Jeremiah's Persecution",
        "21": "God Rejects Zedekiah’s Request",
        "22": "Judgment Against Wicked Kings",
        "23": "The Righteous Branch",
        "24": "The Two Baskets of Figs",
        "25": "Seventy Years of Captivity",
        "26": "Jeremiah Threatened with Death",
        "27": "The Yoke of Nebuchadnezzar",
        "28": "The False Prophet Hananiah",
        "29": "A Letter to the Exiles",
        "30": "Restoration of Israel and Judah",
        "31": "The New Covenant",
        "32": "Jeremiah Buys a Field",
        "33": "Promise of Restoration",
        "34": "Warning to Zedekiah",
        "35": "The Recabites' Obedience",
        "36": "Jehoiakim Burns Jeremiah’s Scroll",
        "37": "Jeremiah Imprisoned",
        "38": "Jeremiah Thrown into a Cistern",
        "39": "The Fall of Jerusalem",
        "40": "Jeremiah Freed and Remains in Judah",
        "41": "The Assassination of Gedaliah",
        "42": "Warning Against Going to Egypt",
        "43": "The People Go to Egypt",
        "44": "Judgment for Idolatry in Egypt",
        "45": "A Message to Baruch",
        "52": "The Fall of Jerusalem Recounted",
    ],
    "Lamentations": [
        "1": "The Desolation of Jerusalem",
        "2": "God's Anger at Sin",
        "3": "Hope in the Midst of Affliction",
        "4": "The Siege of Jerusalem",
        "5": "A Plea for Restoration",
    ],
    "Ezekiel": [
        "1": "Ezekiel's Vision of God's Glory",
        "2": "Ezekiel's Call and Commission",
        "3": "Ezekiel as a Watchman",
        "4": "Symbolic Siege of Jerusalem",
        "5": "Judgment Against Jerusalem",
        "6": "Prophecy Against the Mountains of Israel",
        "7": "The End Has Come",
        "8": "Idolatry in the Temple",
        "9": "Execution of the Idolaters",
        "10": "God's Glory Departs from the Temple",
        "11": "Judgment and Promise of Restoration",
        "12": "Symbolic Actions of Exile",
        "13": "Prophecy Against False Prophets",
        "14": "Idolaters Condemned",
        "15": "Jerusalem as a Useless Vine",
        "16": "Jerusalem's Unfaithfulness",
        "17": "Two Eagles and a Vine",
        "18": "The Soul Who Sins Will Die",
        "19": "Lament for the Princes of Israel",
        "20": "Rebellion of Israel",
        "21": "Babylon as God's Sword of Judgment",
        "22": "Sins of Jerusalem",
        "23": "Oholah and Oholibah",
        "24": "The Cooking Pot and Ezekiel's Wife Dies",
        "33": "Ezekiel as Watchman Renewed",
        "34": "Prophecy Against the Shepherds of Israel",
        "35": "Prophecy Against Mount Seir",
        "36": "Restoration of Israel",
        "37": "The Valley of Dry Bones",
    ],
    "Daniel": [
        "1": "Daniel's Training in Babylon",
        "2": "Nebuchadnezzar's Dream",
        "3": "The Fiery Furnace",
        "4": "Nebuchadnezzar's Second Dream",
        "5": "The Writing on the Wall",
        "6": "Daniel in the Lions' Den",
        "7": "Daniel's Vision of Four Beasts",
        "8": "Vision of the Ram and the Goat",
        "9": "Daniel's Prayer and the Seventy Weeks",
        "10": "Daniel's Vision of a Man",
        "11": "Kings of the South and North",
        "12": "The End Times",
    ],
    "Hosea": [
        "1": "Hosea's Unfaithful Wife",
        "2": "Israel's Unfaithfulness and God's Mercy",
        "3": "Hosea's Reconciliation with Gomer",
        "4": "God's Charges Against Israel",
        "5": "Judgment on Israel and Judah",
        "6": "A Call to Repentance",
        "7": "Israel's Iniquity and Pride",
        "8": "Israel Reaps the Whirlwind",
        "9": "Punishment for Israel",
        "10": "Israel's Sin and Captivity",
        "11": "God's Love for Israel",
        "12": "Israel's Sin and God's Response",
        "13": "God's Anger Against Israel",
        "14": "Return to the Lord",
    ],
    "Joel": [
        "1": "The Locust Plague",
        "2": "The Day of the Lord",
        "3": "Judgment and Blessings",
    ],
    "Amos": [
        "1": "Judgment on Surrounding Nations",
        "2": "Judgment on Moab, Judah, and Israel",
        "3": "Witnesses Against Israel",
        "4": "Israel's Failure to Return to God",
        "5": "A Call to Repentance",
        "6": "Woe to the Complacent",
        "7": "Visions of Judgment",
        "8": "The Basket of Ripe Fruit",
        "9": "Israel's Destruction and Restoration",
    ],
    "Obadiah": [
        "1": "Judgment on Edom"
    ],
    "Jonah": [
        "1": "Jonah Flees from the Lord",
        "2": "Jonah's Prayer",
        "3": "Jonah Goes to Nineveh",
        "4": "Jonah's Anger and God's Compassion",
    ],
    "Micah": [
        "1": "Judgment Against Samaria and Jerusalem",
        "2": "Woe to Oppressors",
        "3": "Leaders and Prophets Rebuked",
        "4": "The Mountain of the Lord",
        "5": "A Ruler from Bethlehem",
        "6": "The Lord's Case Against Israel",
        "7": "Israel's Misery and Hope",
    ],
    "Nahum": [
        "1": "The Lord's Anger Against Nineveh",
        "2": "The Fall of Nineveh",
        "3": "Woe to Nineveh",
    ],
    "Habakkuk": [
        "1": "Habakkuk's Complaint",
        "2": "The Lord's Answer",
        "3": "Habakkuk's Prayer",
    ],
    "Zephaniah": [
        "1": "The Coming Judgment on Judah",
        "2": "A Call to Repentance and Judgment on Nations",
        "3": "Jerusalem's Sin and Redemption",
    ],
    "Haggai": [
        "1": "A Call to Rebuild the Temple",
        "2": "Promised Glory of the New House",
    ],
    "Zechariah": [
        "1": "A Call to Return to the Lord",
        "2": "A Man with a Measuring Line",
        "3": "Clean Garments for the High Priest",
        "4": "The Gold Lampstand and the Two Olive Trees",
        "5": "The Flying Scroll and the Woman in a Basket",
        "6": "Four Chariots and the Crown for Joshua",
        "7": "Justice and Mercy, Not Fasting",
        "8": "The Lord Promises to Bless Jerusalem",
    ],
    "Malachi": [
        "1": "Israel Doubts God's Love",
        "2": "Admonition for Priests and People",
        "3": "The Messenger of the Covenant",
        "4": "The Great Day of the Lord",
    ],
    "Matthew": [
        "1": "The Genealogy and Birth of Jesus",
        "2": "The Visit of the Magi and Flight to Egypt",
        "3": "John the Baptist Prepares the Way",
        "4": "The Temptation of Jesus and Beginning of Ministry",
        "5": "The Sermon on the Mount Begins",
        "6": "Teaching on Righteousness and Prayer",
        "7": "Conclusion of the Sermon on the Mount",
        "8": "Miracles of Healing and Authority",
        "9": "Further Miracles and Calling of Matthew",
        "10": "Sending Out the Twelve Apostles",
        "11": "John the Baptist and Unrepentant Towns",
        "12": "Lord of the Sabbath and Opposition",
        "13": "Parables of the Kingdom",
        "14": "John the Baptist's Death and Feeding the Five Thousand",
        "15": "Traditions and Miracles",
        "16": "Peter's Confession and Prediction of Death",
        "17": "The Transfiguration",
        "18": "Teachings on the Kingdom and Forgiveness",
        "19": "Teachings on Divorce, Children, and Wealth",
        "20": "Parables and Predictions",
        "21": "Triumphal Entry and Cleansing the Temple",
        "22": "Parables and Teachings",
        "23": "Woes to the Scribes and Pharisees",
        "24": "Signs of the End Times",
        "25": "Parables about Readiness and Judgment",
        "26": "Plot Against Jesus and the Last Supper",
        "27": "Trial, Crucifixion, and Death of Jesus",
        "28": "The Resurrection and Great Commission",
    ],
    "Mark": [
        "1": "John the Baptist and the Beginning of Jesus' Ministry",
        "2": "Controversies with Religious Leaders",
        "3": "Healing and Appointment of the Twelve Apostles",
        "4": "Parables of the Kingdom",
        "5": "Healing of the Demon-Possessed Man and Others",
        "6": "Rejection at Nazareth and Feeding the Five Thousand",
        "7": "Teachings on Clean and Unclean",
        "8": "Feeding the Four Thousand and Peter's Confession",
        "9": "The Transfiguration and Teaching on Servanthood",
        "10": "Teachings on Divorce, Wealth, and Service",
        "11": "Triumphal Entry and Cleansing the Temple",
        "12": "Parables and Teachings in the Temple",
        "13": "Signs of the End Times",
        "14": "The Plot Against Jesus and the Last Supper",
        "15": "Trial, Crucifixion, and Death of Jesus",
        "16": "The Resurrection",
    ],
    "Luke": [
        "1": "The Births of John the Baptist and Jesus Foretold",
        "2": "The Birth of Jesus and Early Life",
        "3": "John the Baptist and Genealogy of Jesus",
        "4": "Temptation of Jesus and Beginning of Ministry",
        "5": "Calling of the First Disciples and Miracles",
        "6": "Teachings and Healing on the Sabbath",
        "7": "Miracles and Teachings",
        "8": "Parables and Miracles",
        "9": "Mission of the Twelve and Transfiguration",
        "10": "Mission of the Seventy-Two and Parable of the Good Samaritan",
        "11": "Teaching on Prayer and Warnings",
        "12": "Teaching on Discipleship and Warnings",
        "13": "Repentance, Parables, and Healing",
        "14": "Parables about Humility and Discipleship",
        "15": "Parables of the Lost",
        "16": "Parables on Stewardship and Teachings",
        "17": "Teachings and Miracles",
        "18": "Parables on Prayer and Teachings",
        "19": "Zacchaeus and Parables",
        "20": "Challenges and Teachings in the Temple",
        "21": "Teaching on the End Times",
        "22": "The Last Supper and Betrayal",
        "23": "Trial, Crucifixion, and Death of Jesus",
        "24": "The Resurrection and Appearances of Jesus",
    ],
    "John": [
        "1": "The Word Became Flesh",
        "2": "The Wedding at Cana and Cleansing the Temple",
        "3": "Jesus and Nicodemus",
        "4": "The Samaritan Woman and Healing",
        "5": "Healing at the Pool and Authority of the Son",
        "6": "Feeding the Five Thousand and Bread of Life",
        "7": "Teaching at the Festival of Tabernacles",
        "8": "The Woman Caught in Adultery and Light of the World",
        "9": "Healing of the Man Born Blind",
        "10": "The Good Shepherd",
        "11": "The Raising of Lazarus",
        "12": "Anointing at Bethany and Triumphal Entry",
        "13": "The Last Supper and New Commandment",
        "14": "Jesus Comforts His Disciples",
        "15": "The Vine and the Branches",
        "16": "Work of the Holy Spirit",
        "17": "Jesus' High Priestly Prayer",
        "18": "Jesus' Arrest and Peter's Denial",
        "19": "Crucifixion and Death of Jesus",
        "20": "The Resurrection",
        "21": "Jesus Appears to Seven Disciples and Restores Peter",
    ],
    "Acts": [
        "1": "Ascension of Jesus and Choosing Matthias",
        "2": "The Day of Pentecost",
        "3": "Healing of the Lame Man",
        "4": "Peter and John Before the Sanhedrin",
        "5": "Ananias and Sapphira; Apostles Persecuted",
        "6": "Choosing of the Seven",
        "7": "Stephen's Speech and Martyrdom",
        "8": "Persecution and Philip's Ministry",
        "9": "Conversion of Saul",
        "10": "Peter and Cornelius",
        "11": "Peter Explains His Actions",
        "12": "Peter's Miraculous Escape and Herod's Death",
        "13": "Paul's First Missionary Journey Begins",
        "14": "Ministry in Iconium, Lystra, and Derbe",
        "15": "The Council at Jerusalem",
        "16": "Second Missionary Journey Begins",
        "17": "Preaching in Thessalonica, Berea, and Athens",
        "18": "Ministry in Corinth",
        "19": "Paul in Ephesus",
        "20": "Journey to Jerusalem and Farewell to Ephesian Elders",
        "21": "Paul's Arrival in Jerusalem",
        "22": "Paul's Defense and Roman Citizenship",
        "23": "Paul Before the Sanhedrin",
        "24": "Trial Before Governor Felix",
        "25": "Paul Appeals to Caesar",
        "26": "Paul's Defense Before King Agrippa",
        "27": "Paul's Journey to Rome and Shipwreck",
        "28": "Paul on Malta and Arrival in Rome",
    ],
    "Romans": [
        "1": "The Gospel and Humanity's Sinfulness",
        "2": "God's Righteous Judgment",
        "3": "No One is Righteous",
        "4": "Abraham Justified by Faith",
        "5": "Peace and Hope Through Christ",
        "6": "Dead to Sin, Alive in Christ",
        "7": "Released from the Law",
        "8": "Life Through the Spirit",
        "9": "God's Sovereign Choice",
        "10": "Salvation for All",
        "11": "The Remnant of Israel",
        "12": "Living Sacrifices and Humble Service",
        "13": "Submission to Authorities and Love",
        "14": "The Weak and the Strong",
        "15": "Unity and Paul's Plan to Visit Rome",
        "16": "Personal Greetings and Final Instructions",
    ],
    "1 Corinthians": [
        "1": "Divisions in the Church",
        "2": "Wisdom from the Spirit",
        "3": "Foundation in Christ",
        "4": "The Ministry of Apostles",
        "5": "Dealing with Immorality",
        "6": "Lawsuits and Sexual Purity",
        "7": "Marriage and Singleness",
        "8": "Food Offered to Idols",
        "9": "Paul's Rights as an Apostle",
        "10": "Warnings from Israel's History",
        "11": "Propriety in Worship",
        "12": "Spiritual Gifts and Unity",
        "13": "The Excellence of Love",
        "14": "Orderly Worship",
        "15": "The Resurrection",
        "16": "Final Instructions and Greetings",
    ],
    "2 Corinthians": [
        "1": "Paul's Suffering and Comfort",
        "2": "Forgiveness for the Offender",
        "3": "Ministers of the New Covenant",
        "4": "Treasures in Jars of Clay",
        "5": "The Ministry of Reconciliation",
        "6": "Paul's Hardships",
        "7": "Paul's Joy Over the Church's Repentance",
        "8": "Generosity Encouraged",
        "9": "The Cheerful Giver",
        "10": "Paul Defends His Ministry",
        "11": "Paul's Sufferings",
        "12": "Paul's Vision and Thorn",
        "13": "Final Warnings and Greetings",
    ],
    "Galatians": [
        "1": "Paul's Defense of His Apostleship",
        "2": "Justification by Faith",
        "3": "Faith and the Law",
        "4": "Heirs and Adoption",
        "5": "Freedom in Christ",
        "6": "Bearing One Another's Burdens",
    ],
    "Colossians": [
        "1": "The Supremacy of Christ",
        "2": "Warning Against False Teachings",
        "3": "Christian Living",
        "4": "Living as Ambassadors for Christ",
    ],
    "1 Thessalonians": [
        "1": "Thanksgiving and Encouragement",
        "2": "Paul's Ministry in Thessalonica",
        "3": "Paul's Concern for the Thessalonians",
        "4": "Living in Purity and Hope in the Resurrection",
    ],
    "2 Thessalonians": [
        "1": "God's Justice and Vindication",
        "2": "The Man of Lawlessness and the Day of the Lord",
        "3": "Instructions to the Faithful and Warnings Against the Idle",
    ],
    "1 Timothy": [
        "1": "Paul's Charge to Timothy",
        "2": "Instructions on Worship and Gender Roles",
        "3": "Qualifications for Overseers and Deacons",
    ],
    "2 Timothy": [
        "1": "Paul's Encouragement and Instructions",
        "2": "Strengthen the Faithful and Handle False Teachers",
        "3": "Warnings About the Last Days",
        "4": "Paul's Final Charge and Exhortation",
    ],
    "Titus": [
        "1": "Appointing Elders in Crete",
    ],
    "Philemon": [
        "1": "Paul's Appeal for Onesimus",
    ],
    "Hebrews": [
        "1": "The Supremacy of Christ",
        "2": "Jesus as High Priest",
        "3": "Jesus Greater Than Moses",
        "4": "Sabbath Rest",
        "5": "Jesus as High Priest",
        "6": "Perseverance and Warning",
        "7": "Melchizedek and Jesus' Priesthood",
        "8": "The New Covenant",
        "9": "The Earthly Sanctuary and Christ's Sacrifice",
        "10": "Christ's Sacrifice and the New Way",
        "11": "Faith in Action",
        "12": "Endurance and Holiness",
        "13": "Instructions for Leaders and the End Times",
        "14": "Accepting Differences in the Church",
        "15": "Unity and Final Greetings",
        "16": "Personal Greetings and Final Instructions",
    ],
    "James": [
        "1": "Trials and Temptations",
        "2": "Faith and Deeds",
        "3": "Taming the Tongue",
        "4": "Warning Against Worldliness",
        "5": "Warning to the Rich and Patience in Suffering",
    ],
    "1 Peter": [
        "1": "Hope and Holiness",
        "2": "Living Stones and a Chosen People",
        "3": "Submission and Suffering",
        "4": "Living for God",
        "5": "Shepherding the Flock",
    ],
    "2 Peter": [
        "1": "Growing in Grace and Knowledge",
        "2": "False Teachers and Their Destruction",
        "3": "The Day of the Lord and Remembrance of Moses",
    ],
    "1 John": [
        "1": "Fellowship with God and Walking in the Light",
        "2": "Obedience and Love",
        "3": "Children of God and Love",
        "4": "God is Love and Testing Spirits",
        "5": "Faithful Witnesses and Prayer for the Sick",
    ],
    "2 John": [
        "1": "Walking in Truth and Love",
    ],
    "3 John": [
        "1": "Hospitality and Truth",
    ],
    "Jude": [
        "1": "Contending for the Faith",
    ],
    "Revelation": [
        "1": "Introduction and Vision of the Son of Man",
        "2": "Messages to the Churches in Ephesus, Smyrna, Pergamum, and Thyatira",
        "3": "Messages to the Churches in Sardis, Philadelphia, and Laodicea",
        "4": "Vision of God's Throne in Heaven",
        "5": "The Scroll and the Lamb",
        "6": "The Seals and the Four Horsemen",
        "7": "The Sealing of the 144,000 and the Great Multitude",
        "8": "The Seventh Seal and the Golden Censer",
        "9": "The Fifth and Sixth Trumpets",
        "10": "The Mighty Angel and the Little Scroll",
        "11": "The Two Witnesses and the Seventh Trumpet",
        "12": "The Woman, the Dragon, and the Male Child",
        "13": "The Beast from the Sea and the Beast from the Earth",
        "14": "The Lamb, the 144,000, and Messages of Judgment",
        "15": "The Seven Angels with Seven Plagues",
        "16": "The Seven Bowls of God's Wrath",
        "17": "The Woman on the Beast and the Kings of the Earth",
        "18": "The Fall of Babylon",
        "19": "The Marriage of the Lamb and the Rider on the White Horse",
        "20": "The Thousand Years and Final Judgment",
        "21": "A New Heaven and a New Earth",
        "22": "The River of Life and Final Exhortations",
    ],
]
