"""Per-day content for the "Summer in the Psalms" In-App Event (30 days).

Single source of truth. `gen_plan.py` builds each reflection by pulling the
verbatim KJV text of the chosen `verses` from ios/swiftbible/Text/bible.json and
weaving it with the commentary here, then emits the iOS Swift plan (spliced
into AppEvent.swift) and the Android Kotlin list.

Per day:
  intro       — one framing line before the verses
  verses      — the 3–5 key verses to quote (verbatim text pulled from bible.json)
  comment     — {verse_number: one- or two-sentence reflection shown after it}
  conclusion  — closing line
The full psalm (start..end) opens via the "Read in Bible" button, so we quote
only the load-bearing verses, not the whole thing.

Voice: Adam's reverent register (Mode D — restrained, scripture-direct, grace
not bravado) with Matt Bassford's tells (the drift, the paradox turn, the
verdict close). Don't name Matt in reader-facing text. We never type verse
text here — only commentary — so scripture stays verbatim.
"""

PLAN_NAME = "summerPsalmsReadingPlan"

DAYS = [
    {
        "id": "summer-psalms-2026-day-1",
        "date_iso": "2026-07-01T00:00:00Z",
        "theme": "The Two Ways",
        "book": "Psalms", "chapter": 1, "start": 1, "end": 6,
        "intro": "The Psalter opens with a fork in the road, not a prayer.",
        "verses": [1, 3, 6],
        "comment": {
            1: "Watch the verbs — walk, stand, sit. Nobody sits down in the scorner's seat on day one; you drift there a degree at a time.",
            3: "The blessed life isn't gritted willpower. It's being planted by water — rooted, fed, fruitful in its season.",
            6: "Two ways, two endings. One path the LORD knows; the other blows off like chaff.",
        },
        "conclusion": "Thirty days in the Psalms is thirty days of sinking roots. Start here.",
    },
    {
        "id": "summer-psalms-2026-day-2",
        "date_iso": "2026-07-02T00:00:00Z",
        "theme": "The Shepherd",
        "book": "Psalms", "chapter": 23, "start": 1, "end": 6,
        "intro": "Six verses you think you already know. Read them slow anyway.",
        "verses": [1, 4, 6],
        "comment": {
            1: "If the LORD is the shepherd, \"shall not want\" follows. The restless wanting quiets when he's the one leading.",
            4: "He never promises a way around the valley — only company through it. The rod and staff don't pave the road; they walk it with you.",
            6: "Goodness and mercy don't just meet you. They follow you, all the way home.",
        },
        "conclusion": "The promise was never an easy way. It was Someone on the way with you.",
    },
    {
        "id": "summer-psalms-2026-day-3",
        "date_iso": "2026-07-03T00:00:00Z",
        "theme": "I Lift My Eyes",
        "book": "Psalms", "chapter": 121, "start": 1, "end": 8,
        "intro": "A pilgrim song, sung on the climb up to Jerusalem — eyeing the hills where the road turned dangerous.",
        "verses": [1, 4, 8],
        "comment": {
            1: "Eyes go up to the hills, where bandits hid and help felt far off.",
            4: "The God who built those hills doesn't doze off halfway up yours.",
            8: "Your going out and your coming in — the whole trip, both directions, kept.",
        },
        "conclusion": "Whatever you're climbing toward this summer, you are kept. Keep climbing.",
    },
    {
        "id": "summer-psalms-2026-day-4",
        "date_iso": "2026-07-04T00:00:00Z",
        "theme": "The Shelter",
        "book": "Psalms", "chapter": 91, "start": 1, "end": 16,
        "intro": "Dwell, not visit. This psalm is for the one who lives in God, not the one who drops by when the weather turns.",
        "verses": [1, 4, 11],
        "comment": {
            1: "The secret place isn't a hideout you find in a panic. It's an address you already live at.",
            4: "He doesn't promise no arrows — he promises cover in the middle of them. A wing isn't armor; it's nearness.",
            11: "Angels under orders, charged to keep you. You are not walking unguarded.",
        },
        "conclusion": "Dwelling is a daily address, not an emergency exit. Move in.",
    },
    {
        "id": "summer-psalms-2026-day-5",
        "date_iso": "2026-07-05T00:00:00Z",
        "theme": "Light and Salvation",
        "book": "Psalms", "chapter": 27, "start": 1, "end": 14,
        "intro": "Fear asks \"what if.\" David asks back: whom?",
        "verses": [1, 4, 14],
        "comment": {
            1: "If the LORD is your light, the dark loses its vote. If he's your salvation, the threat loses its teeth.",
            4: "Out of everything he could ask, he asks one thing — to be where God is, and to look at him.",
            14: "The hardest command in the psalm: wait. And when you're done waiting, wait again.",
        },
        "conclusion": "Courage here isn't the absence of enemies. It's knowing whose house you're headed to.",
    },
    {
        "id": "summer-psalms-2026-day-6",
        "date_iso": "2026-07-06T00:00:00Z",
        "theme": "Be Still",
        "book": "Psalms", "chapter": 46, "start": 1, "end": 11,
        "intro": "Not a distant help — a present one, already in the room before the trouble started.",
        "verses": [1, 2, 10],
        "comment": {
            1: "Refuge and strength: a place to hide and the power to stand. He is both.",
            2: "Let the worst happen — earth gone, mountains in the sea — and the psalm still won't panic.",
            10: "\"Be still\" isn't a mood; it's a command. Stop scrambling long enough to remember who outranks the storm.",
        },
        "conclusion": "Stillness isn't the absence of the storm. It's knowing God is God in the middle of it.",
    },
    {
        "id": "summer-psalms-2026-day-7",
        "date_iso": "2026-07-07T00:00:00Z",
        "theme": "Wait in Silence",
        "book": "Psalms", "chapter": 62, "start": 1, "end": 12,
        "intro": "Twice David says it: God only. Not God-plus-a-backup-plan.",
        "verses": [1, 5, 8],
        "comment": {
            1: "The soul that waits in silence isn't passive. It's done auditioning other saviors.",
            5: "He has to tell his own soul to wait — because the soul keeps drifting back to lesser hopes.",
            8: "Pour it all out, every hour, in front of him. He can take the whole weight; he is the refuge.",
        },
        "conclusion": "Wait in silence. And mean the \"only.\"",
    },
    {
        "id": "summer-psalms-2026-day-8",
        "date_iso": "2026-07-08T00:00:00Z",
        "theme": "You Will Not Abandon",
        "book": "Psalms", "chapter": 16, "start": 1, "end": 11,
        "intro": "A simple discipline runs under this whole psalm: keep the LORD in front of you.",
        "verses": [8, 10, 11],
        "comment": {
            8: "Not behind, for emergencies — in front, always. Set there on purpose, you will not be moved.",
            10: "David's hope outruns the grave. Peter preached this very line over the empty tomb.",
            11: "The path of life leads somewhere specific: his presence, where joy is full and the pleasures don't run out.",
        },
        "conclusion": "Set him before you, and start the day there.",
    },
    {
        "id": "summer-psalms-2026-day-9",
        "date_iso": "2026-07-09T00:00:00Z",
        "theme": "How Majestic",
        "book": "Psalms", "chapter": 8, "start": 1, "end": 9,
        "intro": "Stand under a real night sky and this psalm writes itself.",
        "verses": [1, 4, 5],
        "comment": {
            1: "His name fills the earth and the heavens at once — bigness you can't get under or around.",
            4: "All of that, and he bothers with us. The wonder isn't that we're small; it's that he's mindful.",
            5: "Not crushed by the cosmos but crowned. Hebrews reads this as the Son of Man who took the low place to lift ours.",
        },
        "conclusion": "Look up tonight. Let it be worship.",
    },
    {
        "id": "summer-psalms-2026-day-10",
        "date_iso": "2026-07-10T00:00:00Z",
        "theme": "The Heavens Declare",
        "book": "Psalms", "chapter": 19, "start": 1, "end": 14,
        "intro": "Two sermons in one psalm, and neither needs translating.",
        "verses": [1, 7, 14],
        "comment": {
            1: "The sky preaches without a word — and there's no language where its voice isn't heard.",
            7: "Then the second sermon: the law of the LORD, perfect, actually able to convert a soul.",
            14: "So the prayer turns inward — let even my words and my thoughts be acceptable to him.",
        },
        "conclusion": "Creation tells you there's a God. The Word tells you his name. Let the last verse be your prayer.",
    },
    {
        "id": "summer-psalms-2026-day-11",
        "date_iso": "2026-07-11T00:00:00Z",
        "theme": "Bless the LORD (Creation)",
        "book": "Psalms", "chapter": 104, "start": 1, "end": 35,
        "intro": "A tour of creation with the Maker named on every page.",
        "verses": [1, 24, 33],
        "comment": {
            1: "He wears light like a robe. Majesty isn't decoration on God; it's what he's clothed in.",
            24: "Look closely and the count overwhelms you — every wild and ordinary thing made in wisdom.",
            33: "Nothing here runs itself; it's all held. The only fitting response is to sing while you've got breath.",
        },
        "conclusion": "Worship isn't analysis. It's the song creation has been singing all along.",
    },
    {
        "id": "summer-psalms-2026-day-12",
        "date_iso": "2026-07-12T00:00:00Z",
        "theme": "Bless the LORD, O My Soul",
        "book": "Psalms", "chapter": 103, "start": 1, "end": 22,
        "intro": "David preaches to himself here. Sometimes the soul needs telling, not asking.",
        "verses": [2, 12, 14],
        "comment": {
            2: "\"Forget not\" — because we do. The benefits stack up and we stop counting them.",
            12: "East and west never meet; the distance has no middle. That's how far he's carried your sin.",
            14: "He isn't surprised by your weakness. He remembers the dust you're made of, and loves you anyway.",
        },
        "conclusion": "Forget not all his benefits. Bless the LORD, O my soul.",
    },
    {
        "id": "summer-psalms-2026-day-13",
        "date_iso": "2026-07-13T00:00:00Z",
        "theme": "Make a Joyful Noise",
        "book": "Psalms", "chapter": 100, "start": 1, "end": 5,
        "intro": "Five verses, almost all command. Praise isn't a feeling you wait for; it's a thing you do until the feeling catches up.",
        "verses": [1, 3, 5],
        "comment": {
            1: "A joyful noise — not necessarily a tuneful one. He's after gladness, not performance.",
            3: "Know it: he made us, not the other way around. We're the sheep, not the shepherd.",
            5: "And the ground under all the noise — his goodness, his mercy, his truth, with no expiration date.",
        },
        "conclusion": "Enter his gates with thanksgiving. Make some noise.",
    },
    {
        "id": "summer-psalms-2026-day-14",
        "date_iso": "2026-07-14T00:00:00Z",
        "theme": "I Will Extol Thee",
        "book": "Psalms", "chapter": 145, "start": 1, "end": 21,
        "intro": "David walks the alphabet to praise God — like he's using every letter he has and still coming up short.",
        "verses": [2, 8, 18],
        "comment": {
            2: "Every day, not the good ones only. Praise as a daily habit, not a mood that visits.",
            8: "Here's the God he's praising: gracious, full of compassion, slow to anger, great in mercy.",
            18: "And near — near to everyone who calls. Not far off for the worthy; near for the asking.",
        },
        "conclusion": "Great is the LORD, and greatly to be praised. Every day. Start with this one.",
    },
    {
        "id": "summer-psalms-2026-day-15",
        "date_iso": "2026-07-15T00:00:00Z",
        "theme": "Sing a New Song",
        "book": "Psalms", "chapter": 96, "start": 1, "end": 13,
        "intro": "A new song, because the mercies aren't yesterday's. Old gratitude goes stale.",
        "verses": [1, 3, 9],
        "comment": {
            1: "Sing something new — and not just you. \"All the earth\" is invited into the chorus.",
            3: "Praise that's real wants witnesses; it declares his glory instead of keeping it private.",
            9: "Worship him in the beauty of holiness. Awe, not just enthusiasm.",
        },
        "conclusion": "Find a fresh song today. Then sing it where someone can hear.",
    },
    {
        "id": "summer-psalms-2026-day-16",
        "date_iso": "2026-07-16T00:00:00Z",
        "theme": "How Long?",
        "book": "Psalms", "chapter": 13, "start": 1, "end": 6,
        "intro": "Four \"how longs\" in two verses. The Bible lets you talk to God like this.",
        "verses": [1, 5, 6],
        "comment": {
            1: "Honesty isn't the opposite of faith — it's faith refusing to leave the room.",
            5: "Then the hinge the whole psalm turns on: but. He trusted in mercy before the feelings changed.",
            6: "From \"how long\" to \"I will sing\" in six verses. The complaint didn't get the last word.",
        },
        "conclusion": "Lament is allowed. So is the turn. Don't stop before verse 5.",
    },
    {
        "id": "summer-psalms-2026-day-17",
        "date_iso": "2026-07-17T00:00:00Z",
        "theme": "As the Hart Panteth",
        "book": "Psalms", "chapter": 42, "start": 1, "end": 11,
        "intro": "A thirst, not a preference. The deer isn't browsing; it's desperate.",
        "verses": [1, 3, 5],
        "comment": {
            1: "Some seasons that's exactly how God feels — necessary and absent at once.",
            3: "Tears for food, day and night, while people ask where your God is. The psalm doesn't pretend otherwise.",
            5: "So he turns and talks to himself — names the despair, then preaches hope back at it.",
        },
        "conclusion": "Preach to the soul that won't sing yet. Tell it where to put its hope.",
    },
    {
        "id": "summer-psalms-2026-day-18",
        "date_iso": "2026-07-18T00:00:00Z",
        "theme": "My Soul Thirsteth",
        "book": "Psalms", "chapter": 63, "start": 1, "end": 11,
        "intro": "David wrote this in a wilderness — \"a dry and thirsty land, where no water is.\"",
        "verses": [1, 3, 7],
        "comment": {
            1: "The driest place became the clearest prayer. He seeks God early, before anything else gets in.",
            3: "He doesn't ask to leave the desert. He says what the desert taught him: God's love beats life itself.",
            7: "Even there, in the dark, he finds the shadow of God's wings — and sings.",
        },
        "conclusion": "Thirst isn't your enemy. It's the thing pointing you home. Seek him early.",
    },
    {
        "id": "summer-psalms-2026-day-19",
        "date_iso": "2026-07-19T00:00:00Z",
        "theme": "Have Mercy",
        "book": "Psalms", "chapter": 51, "start": 1, "end": 19,
        "intro": "David after Bathsheba. No spin, no blaming the circumstances.",
        "verses": [1, 10, 17],
        "comment": {
            1: "He throws himself entirely on mercy — according to God's lovingkindness, not his own record.",
            10: "He doesn't ask for a touch-up. He asks to be remade. Create — only God does that verb.",
            17: "And here's what God won't turn away: not performance, but a broken and a contrite heart.",
        },
        "conclusion": "Real repentance stops managing the story and tells the truth. Bring him the broken heart.",
    },
    {
        "id": "summer-psalms-2026-day-20",
        "date_iso": "2026-07-20T00:00:00Z",
        "theme": "Out of the Depths",
        "book": "Psalms", "chapter": 130, "start": 1, "end": 8,
        "intro": "The depths — not the shallows. This prayer comes from the bottom, and still expects to be heard.",
        "verses": [1, 4, 7],
        "comment": {
            1: "He doesn't clean himself up before crying out. He cries out from where he actually is.",
            4: "Why expect mercy? Because there is forgiveness with him. If he marked every sin, who could stand?",
            7: "So he waits like a watchman waits for morning — and morning, with him, is plenteous redemption.",
        },
        "conclusion": "Out of the depths is a fine place to start praying. He's listening there too.",
    },
    {
        "id": "summer-psalms-2026-day-21",
        "date_iso": "2026-07-21T00:00:00Z",
        "theme": "Blessed Is Forgiven",
        "book": "Psalms", "chapter": 32, "start": 1, "end": 11,
        "intro": "Two days ago was the confession. This is the morning after — the plain relief of a clean conscience.",
        "verses": [1, 3, 5],
        "comment": {
            1: "Not erased from history; covered by God, and counted gone. That's the blessing.",
            3: "David remembers the cost of hiding: silence aged his bones. Buried sin doesn't go quiet; it goes inward.",
            5: "Then he came clean — and forgiveness was already waiting on the other side of honesty.",
        },
        "conclusion": "Don't be dragged like a stubborn horse. Come freely. Be glad.",
    },
    {
        "id": "summer-psalms-2026-day-22",
        "date_iso": "2026-07-22T00:00:00Z",
        "theme": "My God, Why?",
        "book": "Psalms", "chapter": 22, "start": 1, "end": 31,
        "intro": "Jesus said the first line of this psalm from the cross. He reached for the loudest complaint in the Psalter.",
        "verses": [1, 16, 22],
        "comment": {
            1: "Forsaken — and he prayed it out loud. Even that cry was addressed to \"my God.\"",
            16: "Then it turns eerie: pierced hands and feet, written a thousand years before a Roman nail.",
            22: "And it turns again — from forsaken to declaring God's name among his brethren. The song doesn't end at the cross.",
        },
        "conclusion": "The most abandoned-sounding psalm is the most exactly fulfilled. Read it to the end.",
    },
    {
        "id": "summer-psalms-2026-day-23",
        "date_iso": "2026-07-23T00:00:00Z",
        "theme": "He Brought Me Up",
        "book": "Psalms", "chapter": 40, "start": 1, "end": 17,
        "intro": "First, the waiting. \"Patiently\" — the rescue was real, and it wasn't instant.",
        "verses": [1, 2, 3],
        "comment": {
            1: "He waited, and he was heard. Both halves are true; one just takes longer.",
            2: "Up out of the pit and the miry clay, feet set on a rock. Stable ground after a long sink.",
            3: "And a new song in his mouth — deliverance hands you something to sing you didn't have before.",
        },
        "conclusion": "Wait. Then, when he's set your feet down, don't keep the song to yourself.",
    },
    {
        "id": "summer-psalms-2026-day-24",
        "date_iso": "2026-07-24T00:00:00Z",
        "theme": "Mourning into Dancing",
        "book": "Psalms", "chapter": 30, "start": 1, "end": 12,
        "intro": "David had been low. He isn't theorizing about pain; he'd been in it.",
        "verses": [3, 5, 11],
        "comment": {
            3: "Brought up from the grave itself. He's writing as someone who got a morning he didn't expect.",
            5: "Weeping may last a night — but a night, not forever. His anger is a moment; his favour is a lifetime.",
            11: "Mourning turned to dancing. He doesn't explain the turn so much as testify to it.",
        },
        "conclusion": "Night is real, and it has an end. Hold on till morning.",
    },
    {
        "id": "summer-psalms-2026-day-25",
        "date_iso": "2026-07-25T00:00:00Z",
        "theme": "Taste and See",
        "book": "Psalms", "chapter": 34, "start": 1, "end": 22,
        "intro": "Taste — not read about, not hear secondhand. Some things about God you only learn by trying him.",
        "verses": [4, 8, 18],
        "comment": {
            4: "David's testimony is specific: he sought, God heard, the fears went. Not theory — experience.",
            8: "So he hands you the dare: taste and see. Find out for yourself that he's good.",
            18: "And for the days that don't feel good — he's near the broken-hearted, close to the crushed.",
        },
        "conclusion": "He's near the crushed, not the impressive. Taste and see.",
    },
    {
        "id": "summer-psalms-2026-day-26",
        "date_iso": "2026-07-26T00:00:00Z",
        "theme": "How Amiable",
        "book": "Psalms", "chapter": 84, "start": 1, "end": 12,
        "intro": "Homesick for the house of God. The psalmist even envies the sparrow that gets to nest by the altar.",
        "verses": [1, 2, 10],
        "comment": {
            1: "How lovely, how worth-longing-for, are the places where God meets his people.",
            2: "Not polite interest. His soul faints with longing for the courts of the LORD.",
            10: "A single day there beats a thousand anywhere else. He'd rather hold the door than live easy elsewhere.",
        },
        "conclusion": "And the road counts too — passing through the dry valley, they make it a place of springs.",
    },
    {
        "id": "summer-psalms-2026-day-27",
        "date_iso": "2026-07-27T00:00:00Z",
        "theme": "Searched and Known",
        "book": "Psalms", "chapter": 139, "start": 1, "end": 24,
        "intro": "Fully known — which is more terrifying and more comforting than being half-known and liked.",
        "verses": [1, 7, 23],
        "comment": {
            1: "He knows your sitting down and your rising up, your words before you say them. All of it.",
            7: "And there's nowhere his presence isn't — not heaven, not the grave, not the far side of the sea.",
            23: "So the brave prayer: ask the One who already sees to show you what he sees.",
        },
        "conclusion": "You are completely known and not turned away. Let him search you.",
    },
    {
        "id": "summer-psalms-2026-day-28",
        "date_iso": "2026-07-28T00:00:00Z",
        "theme": "Number Our Days",
        "book": "Psalms", "chapter": 90, "start": 1, "end": 17,
        "intro": "Moses wrote this one. He isn't being morbid about our short years — he's being accurate.",
        "verses": [1, 12, 17],
        "comment": {
            1: "Generations come and go; God has been the dwelling place through every one of them.",
            12: "The prayer isn't for more days. It's to count the ones we have, and spend them on what lasts.",
            17: "And then the ask that redeems a short life: establish the work of our hands. Make it count.",
        },
        "conclusion": "A brief life, made to matter by an eternal God. Number your days.",
    },
    {
        "id": "summer-psalms-2026-day-29",
        "date_iso": "2026-07-29T00:00:00Z",
        "theme": "I Love the LORD",
        "book": "Psalms", "chapter": 116, "start": 1, "end": 19,
        "intro": "Love with a reason attached. He prayed in real trouble, and God heard — so now he loves.",
        "verses": [1, 12, 15],
        "comment": {
            1: "Not abstract devotion. He loves the LORD because the LORD bent down and listened.",
            12: "The honest question of the rescued: what do you give back for grace like that?",
            15: "And a line for the grieving: the death of his saints isn't cheap to him. It's precious in his sight.",
        },
        "conclusion": "You can't repay grace. You can receive it and say so. He has heard you too.",
    },
    {
        "id": "summer-psalms-2026-day-30",
        "date_iso": "2026-07-30T00:00:00Z",
        "theme": "Let Everything Praise",
        "book": "Psalms", "chapter": 150, "start": 1, "end": 6,
        "intro": "The Psalter ends with no request left. After all the lament and waiting, it lands on pure praise.",
        "verses": [1, 2, 6],
        "comment": {
            1: "Praise him where he is — in his sanctuary, in the heights. Start with the place he's promised to be.",
            2: "Praise him for what he's done — his mighty acts — and for who he is — his excellent greatness.",
            6: "And the last instrument is you. If you have breath, you're in the orchestra.",
        },
        "conclusion": "Thirty days, from \"blessed is the man\" to \"praise ye the LORD.\" Take a breath. Use it.",
    },
]
