package biz.am2.swiftbible.ui.components

import androidx.compose.animation.core.RepeatMode
import androidx.compose.animation.core.animateFloat
import androidx.compose.animation.core.infiniteRepeatable
import androidx.compose.animation.core.rememberInfiniteTransition
import androidx.compose.animation.core.tween
import androidx.compose.foundation.background
import androidx.compose.foundation.border
import androidx.compose.foundation.clickable
import androidx.compose.foundation.layout.Box
import androidx.compose.foundation.layout.Row
import androidx.compose.foundation.layout.Spacer
import androidx.compose.foundation.layout.padding
import androidx.compose.foundation.layout.size
import androidx.compose.foundation.shape.CircleShape
import androidx.compose.foundation.shape.RoundedCornerShape
import androidx.compose.material3.AlertDialog
import androidx.compose.material3.MaterialTheme
import androidx.compose.material3.Surface
import androidx.compose.material3.Text
import androidx.compose.material3.TextButton
import androidx.compose.runtime.Composable
import androidx.compose.runtime.getValue
import androidx.compose.runtime.mutableStateOf
import androidx.compose.runtime.remember
import androidx.compose.runtime.setValue
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.draw.clip
import androidx.compose.ui.draw.rotate
import androidx.compose.ui.draw.scale
import androidx.compose.ui.graphics.Brush
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.unit.dp
import androidx.compose.ui.unit.sp
import biz.am2.swiftbible.ui.theme.BrandAccent
import biz.am2.swiftbible.ui.theme.BrandGold
import biz.am2.swiftbible.ui.theme.BrandGoldLight
import biz.am2.swiftbible.ui.theme.BrandPeridot
import biz.am2.swiftbible.ui.theme.BrandRed

object AIAttribution {
    const val FALLBACK_MODEL = "GPT-5.6 Terra"
    private const val DISCLAIMER =
        "Large language models can make mistakes, produce inaccurate information, " +
            "or generate content that may not align with biblical teaching. Always verify " +
            "important information and consult trusted sources."

    fun devotionalSingle(model: String?): String =
        "This devotional was generated by ${displayName(model)} via OpenAI from a single Bible verse. $DISCLAIMER"

    fun devotionalDual(model: String?): String =
        "This devotional was generated by ${displayName(model)} via OpenAI, weaving together verses from two thematically connected Bible books. $DISCLAIMER"

    fun devotionalHoliday(name: String, model: String?): String =
        "This devotional was generated by ${displayName(model)} in honor of $name. $DISCLAIMER"

    const val STYLE_EMPATHY =
        "Empathy style — written to meet you where you are. It opens by naming a real human " +
            "struggle, weaves Scripture into that moment, and closes with a prayer rather than a checklist."

    const val STYLE_TECHNICAL =
        "Technical style — leans into the original Hebrew or Greek, historical context, and a " +
            "structured walk through what the verse actually says before applying it to today."

    const val STYLE_NARRATIVE =
        "Narrative style — drops you inside the biblical scene. Present tense, sensory, observational. " +
            "Stays close to what scripture actually supplies — no invented dialogue, no guessed motivations."

    const val STYLE_PRACTICAL =
        "Practical style — one concrete action for today. Plain language, honest about the cost. " +
            "No \"five ways to...\" — just the one thing the verse is asking of you."

    // Style names describe the method, never the preacher whose archive the
    // track's voice profile was derived from. These are not attributions.
    const val STYLE_PLAINSPOKEN =
        "Plainspoken style — short, flat sentences that land like verdicts. Opens on something " +
            "ordinary, stays precise about what the text actually says, and closes with a few " +
            "blunt imperatives instead of a summary."

    const val STYLE_CLASSROOM =
        "Classroom style — opens with a real question, then earns the passage by setting up its " +
            "world first: who wrote it, to whom, and what the words meant then. Says plainly " +
            "where the text doesn't settle a question."

    const val STYLE_LAMENT =
        "Lament style — for the days that aren't okay. It sits inside the grief of a passage " +
            "without hurrying to comfort, and doesn't explain away pain that scripture itself " +
            "leaves unexplained."

    const val STYLE_QUESTION =
        "Question style — takes one honest question seriously, including the uncomfortable form " +
            "of it, and separates what scripture states from what it implies. Ends with the " +
            "question sharpened rather than dissolved."

    const val STYLE_PORTRAIT =
        "Portrait style — one person in scripture across a whole arc: who they were, what " +
            "happened to them, and what God did with their failure rather than around it."

    fun displayName(raw: String?): String {
        if (raw.isNullOrEmpty()) return FALLBACK_MODEL
        // "gpt-5.6-terra" -> "GPT-5.6 Terra"; anything unexpected falls back to
        // a plain prefix swap so an unknown id still renders sensibly.
        val parts = raw.split("-")
        if (parts.size == 3 && parts[0].lowercase() == "gpt") {
            return "GPT-${parts[1]} ${parts[2].replaceFirstChar { it.uppercase() }}"
        }
        return raw.replace(Regex("(?i)gpt-"), "GPT-")
    }
}

@Composable
fun AnimatedBadgeCircle(
    emoji: String,
    primary: Color,
    secondary: Color,
    tertiary: Color = Color(0xFF7B5BD9),
    size: androidx.compose.ui.unit.Dp = 28.dp,
) {
    val transition = rememberInfiniteTransition(label = "badge")
    val rotation by transition.animateFloat(
        initialValue = 0f,
        targetValue = 360f,
        animationSpec = infiniteRepeatable(animation = tween(2400)),
        label = "rotation",
    )
    val pulse by transition.animateFloat(
        initialValue = 0.92f,
        targetValue = 1.10f,
        animationSpec = infiniteRepeatable(animation = tween(1300), repeatMode = RepeatMode.Reverse),
        label = "pulse",
    )
    val tilt by transition.animateFloat(
        initialValue = -6f,
        targetValue = 6f,
        animationSpec = infiniteRepeatable(animation = tween(1300), repeatMode = RepeatMode.Reverse),
        label = "tilt",
    )

    Box(
        modifier = Modifier.size(size),
        contentAlignment = Alignment.Center,
    ) {
        Box(
            modifier = Modifier
                .matchParentSize()
                .clip(CircleShape)
                .background(MaterialTheme.colorScheme.surface.copy(alpha = 0.75f))
                .border(
                    width = 1.4.dp,
                    brush = Brush.sweepGradient(
                        listOf(
                            primary.copy(alpha = 0.8f),
                            secondary.copy(alpha = 0.4f),
                            tertiary.copy(alpha = 0.6f),
                            primary.copy(alpha = 0.8f),
                        ),
                    ),
                    shape = CircleShape,
                )
                .rotate(rotation),
        )
        Text(
            text = emoji,
            fontSize = (size.value * 0.55f).sp,
            modifier = Modifier
                .scale(pulse)
                .rotate(tilt),
        )
    }
}

@Composable
fun DevotionalBadge(
    devotionalType: String?,
    holidayName: String?,
    model: String?,
) {
    var showDialog by remember { mutableStateOf(false) }
    var dialogTitle by remember { mutableStateOf("") }
    var dialogMessage by remember { mutableStateOf("") }

    fun present(title: String, message: String) {
        dialogTitle = title
        dialogMessage = message
        showDialog = true
    }

    val handle: () -> Unit = when {
        devotionalType == "custom" -> { ->
            present(
                "Hand-crafted devotional",
                "This devotional was personally written by Adam, the developer of SwiftBible, rather than generated by AI.",
            )
        }
        !holidayName.isNullOrBlank() -> { ->
            present(holidayName, AIAttribution.devotionalHoliday(holidayName, model))
        }
        devotionalType == "multi" -> { ->
            present("AI Generated Content", AIAttribution.devotionalDual(model))
        }
        else -> { ->
            present("AI Generated Content", AIAttribution.devotionalSingle(model))
        }
    }

    Surface(
        onClick = handle,
        shape = CircleShape,
        color = Color.Transparent,
        modifier = Modifier.size(34.dp),
    ) {
        Box(modifier = Modifier.size(34.dp), contentAlignment = Alignment.Center) {
            when {
                devotionalType == "custom" -> AnimatedBadgeCircle(
                    emoji = "✍️",
                    primary = BrandGold,
                    secondary = BrandGoldLight,
                    tertiary = BrandPeridot,
                )
                !holidayName.isNullOrBlank() -> {
                    val palette = HolidayBadgePalette.paletteFor(holidayName)
                    AnimatedBadgeCircle(
                        emoji = palette.emoji,
                        primary = palette.primary,
                        secondary = palette.secondary,
                        tertiary = palette.tertiary,
                    )
                }
                devotionalType == "multi" -> AnimatedBadgeCircle(
                    emoji = "✨",
                    primary = BrandAccent,
                    secondary = Color(0xFF3B5BDB),
                )
                else -> AnimatedBadgeCircle(
                    emoji = "💫",
                    primary = Color(0xFFE6B800),
                    secondary = Color(0xFFD9883C),
                )
            }
        }
    }

    if (showDialog) {
        AlertDialog(
            onDismissRequest = { showDialog = false },
            title = { Text(dialogTitle, fontWeight = FontWeight.SemiBold) },
            text = { Text(dialogMessage, style = MaterialTheme.typography.bodyMedium) },
            confirmButton = {
                TextButton(onClick = { showDialog = false }) { Text("OK") }
            },
        )
    }
}

/**
 * Small tinted pill indicating the prompting style ("track") that produced an
 * AI-generated devotional. Driven by the `track` column on the Daily Devotional
 * row (set by the Edge Function's TRACK_CYCLE). Renders nothing for unrecognized
 * tracks or null.
 */
@Composable
fun DevotionalStyleChip(track: String?) {
    val data = when (track) {
        "empathy" -> StyleChipData("💗", "Empathy", Color(0xFFEC4899), AIAttribution.STYLE_EMPATHY)
        "technical" -> StyleChipData("🧠", "Technical", Color(0xFF6366F1), AIAttribution.STYLE_TECHNICAL)
        "narrative" -> StyleChipData("🌅", "Narrative", Color(0xFFF59E0B), AIAttribution.STYLE_NARRATIVE)
        "practical" -> StyleChipData("🛠️", "Practical", Color(0xFF10B981), AIAttribution.STYLE_PRACTICAL)
        "matt" -> StyleChipData("✒️", "Plainspoken", Color(0xFF8D6E63), AIAttribution.STYLE_PLAINSPOKEN)
        "josh" -> StyleChipData("🎓", "Classroom", Color(0xFF009688), AIAttribution.STYLE_CLASSROOM)
        "lament" -> StyleChipData("🕯️", "Lament", Color(0xFF3B82F6), AIAttribution.STYLE_LAMENT)
        "question" -> StyleChipData("🤔", "Question", Color(0xFF06B6D4), AIAttribution.STYLE_QUESTION)
        "character" -> StyleChipData("👤", "Portrait", Color(0xFFA855F7), AIAttribution.STYLE_PORTRAIT)
        else -> return
    }

    var showDialog by remember { mutableStateOf(false) }

    Box(
        modifier = Modifier
            .clip(RoundedCornerShape(50))
            .background(data.tint.copy(alpha = 0.15f))
            .clickable { showDialog = true }
            .padding(horizontal = 10.dp, vertical = 4.dp),
    ) {
        Row(verticalAlignment = Alignment.CenterVertically) {
            Text(text = data.emoji, fontSize = 12.sp)
            Spacer(Modifier.size(4.dp))
            Text(
                text = data.label,
                style = MaterialTheme.typography.labelMedium,
                color = data.tint,
                fontWeight = FontWeight.SemiBold,
            )
        }
    }

    if (showDialog) {
        AlertDialog(
            onDismissRequest = { showDialog = false },
            title = { Text("${data.label} style", fontWeight = FontWeight.SemiBold) },
            text = { Text(data.info, style = MaterialTheme.typography.bodyMedium) },
            confirmButton = {
                TextButton(onClick = { showDialog = false }) { Text("OK") }
            },
        )
    }
}

private data class StyleChipData(
    val emoji: String,
    val label: String,
    val tint: Color,
    val info: String,
)

data class HolidayBadgePalette(
    val emoji: String,
    val primary: Color,
    val secondary: Color,
    val tertiary: Color,
) {
    companion object {
        private val FALLBACK = HolidayBadgePalette("🎁", BrandRed, Color(0xFF8C1F1F), BrandGold)

        @Suppress("CyclomaticComplexMethod", "LongMethod")
        fun paletteFor(name: String): HolidayBadgePalette = when (name) {
            "Christmas Day" -> HolidayBadgePalette("🎁", BrandRed, Color(0xFF33CC66), BrandGold)
            "Christmas Eve" -> HolidayBadgePalette("🌙", BrandRed, Color(0xFF33CC66), BrandGoldLight)
            "First Sunday of Advent" -> HolidayBadgePalette("①", Color(0xFF7B5BD9), Color(0xFF0D1226), BrandGold)
            "Second Sunday of Advent" -> HolidayBadgePalette("②", Color(0xFF7B5BD9), Color(0xFF0D1226), BrandGold)
            "Third Sunday of Advent" -> HolidayBadgePalette("③", Color(0xFFE76FA8), Color(0xFF7B5BD9), BrandGold)
            "Fourth Sunday of Advent" -> HolidayBadgePalette("④", Color(0xFF7B5BD9), Color(0xFF0D1226), BrandGold)
            "Epiphany", "Epiphany Eve" -> HolidayBadgePalette("⭐", BrandGold, Color(0xFF00BFD9), Color.White)
            "Baptism of Jesus" -> HolidayBadgePalette("💧", Color(0xFF00BFD9), BrandGoldLight, BrandAccent)
            "Transfiguration" -> HolidayBadgePalette("☀️", BrandGoldLight, BrandGold, Color.White)
            "Shrove Tuesday" -> HolidayBadgePalette("🎉", BrandGold, Color(0xFF7B5BD9), Color(0xFFFF8C42))
            "Ash Wednesday" -> HolidayBadgePalette("🌫️", Color(0xFF888888), Color(0xFF7B5BD9), Color(0xFF2E1F14))
            "Laetare Sunday" -> HolidayBadgePalette("💖", Color(0xFFE76FA8), BrandGold, Color(0xFF7B5BD9))
            "Palm Sunday" -> HolidayBadgePalette("🌿", Color(0xFFBFD900), Color(0xFF33CC66), BrandGold)
            "Holy Monday", "Spy Wednesday" -> HolidayBadgePalette("🌑", Color(0xFF7B5BD9), Color(0xFF0D1226), Color(0xFF2E1F14))
            "Maundy Thursday" -> HolidayBadgePalette("🍷", BrandRed, Color(0xFF7B5BD9), BrandGold)
            "Good Friday" -> HolidayBadgePalette("✝️", Color(0xFF0D1226), Color(0xFF8C1F1F), Color(0xFF2E1F14))
            "Holy Saturday" -> HolidayBadgePalette("🌒", Color(0xFF0D1226), Color(0xFF888888), Color(0xFF2E1F14))
            "Easter Sunday" -> HolidayBadgePalette("🌞", BrandGoldLight, Color(0xFF00BFD9), BrandGold)
            "Ascension Day" -> HolidayBadgePalette("☁️", Color(0xFF00BFD9), BrandGoldLight, Color.White)
            "Pentecost" -> HolidayBadgePalette("🔥", BrandRed, Color(0xFFFF8C42), BrandGold)
            "Trinity Sunday" -> HolidayBadgePalette("🔺", BrandGold, Color.White, Color(0xFF00BFD9))
            "Reformation Day" -> HolidayBadgePalette("📜", BrandRed, Color(0xFF0D1226), BrandGold)
            "All Saints' Day" -> HolidayBadgePalette("⭐", BrandGold, Color.White, BrandGoldLight)
            "Christ the King Sunday" -> HolidayBadgePalette("👑", BrandGold, BrandRed, Color(0xFF8C1F1F))
            "Michaelmas" -> HolidayBadgePalette("🛡️", BrandRed, BrandGold, Color(0xFF0D1226))
            "New Year's Eve" -> HolidayBadgePalette("🎉", BrandGold, Color(0xFF0D1226), BrandGoldLight)
            "New Year's Day" -> HolidayBadgePalette("🥂", BrandGoldLight, BrandGold, Color(0xFF00BFD9))
            "Mother's Day" -> HolidayBadgePalette("💐", Color(0xFFE76FA8), BrandGoldLight, Color(0xFF7B5BD9))
            "Father's Day" -> HolidayBadgePalette("👔", Color(0xFF3B5BDB), BrandGold, Color(0xFF0D1226))
            "Thanksgiving" -> HolidayBadgePalette("🍂", BrandGold, Color(0xFFFF8C42), Color(0xFF473321))
            "Independence Day", "Flag Day", "Patriot Day" -> HolidayBadgePalette("🎆", BrandRed, Color(0xFF3B5BDB), Color.White)
            "Memorial Day", "Veterans Day" -> HolidayBadgePalette("🇺🇸", BrandRed, Color(0xFF3B5BDB), Color.White)
            "Labor Day" -> HolidayBadgePalette("🔨", Color(0xFF3B5BDB), BrandGold, Color.White)
            "Martin Luther King Jr. Day" -> HolidayBadgePalette("🕊️", Color(0xFF3B5BDB), BrandGold, BrandRed)
            "Presidents' Day" -> HolidayBadgePalette("🏛️", Color(0xFF3B5BDB), BrandRed, Color.White)
            "Election Day" -> HolidayBadgePalette("🗳️", Color(0xFF3B5BDB), BrandRed, Color.White)
            "Juneteenth" -> HolidayBadgePalette("🎊", BrandRed, Color(0xFF33CC66), BrandGold)
            "World Day of Prayer", "National Day of Prayer" -> HolidayBadgePalette("🙏", BrandGold, Color(0xFF00BFD9), Color.White)
            "Valentine's Day" -> HolidayBadgePalette("❤️", Color(0xFFE76FA8), BrandRed, Color(0xFF8C1F1F))
            "St. Patrick's Day" -> HolidayBadgePalette("☘️", Color(0xFF33CC66), Color(0xFFBFD900), BrandGold)
            "International Day of Peace" -> HolidayBadgePalette("☮️", Color(0xFF00BFD9), Color.White, Color(0xFFBFD900))
            "Earth Day" -> HolidayBadgePalette("🌎", Color(0xFF33CC66), Color(0xFFBFD900), Color(0xFF00BFD9))
            "Spring Equinox" -> HolidayBadgePalette("🌷", Color(0xFFBFD900), Color(0xFF33CC66), Color(0xFFE76FA8))
            "Summer Solstice" -> HolidayBadgePalette("☀️", BrandGold, Color(0xFFFF8C42), Color(0xFF00BFD9))
            "Autumn Equinox" -> HolidayBadgePalette("🍁", Color(0xFFFF8C42), BrandRed, BrandGold)
            "Winter Solstice" -> HolidayBadgePalette("❄️", Color(0xFF00BFD9), Color(0xFF0D1226), Color.White)
            else -> FALLBACK
        }
    }
}
