//
//  AIGeneratedBadge.swift
//  swiftbible
//
//  Created by OpenAI.
//

import SwiftUI

struct AIGeneratedBadge: View {
    var message: String = "This text was generated by Apple Intelligence."
    var symbolName: String = "sparkles"

    @State private var showDisclosure = false
    @State private var isAnimating = false

    var body: some View {
        Button {
            showDisclosure = true
        } label: {
            ZStack {
                Circle()
                    .fill(.ultraThinMaterial)
                    .overlay(
                        Circle()
                            .stroke(.secondary.opacity(0.25), lineWidth: 1)
                    )
                    .overlay(
                        Circle()
                            .stroke(
                                AngularGradient(
                                    colors: [
                                        .yellow.opacity(0.8),
                                        .orange.opacity(0.4),
                                        .purple.opacity(0.6),
                                        .yellow.opacity(0.8)
                                    ],
                                    center: .center
                                ),
                                lineWidth: 1.4
                            )
                            .rotationEffect(.degrees(isAnimating ? 360 : 0))
                            .animation(
                                .linear(duration: 2.4)
                                    .repeatForever(autoreverses: false),
                                value: isAnimating
                            )
                    )
                    .shadow(color: .yellow.opacity(0.25), radius: isAnimating ? 4 : 0)
                    .animation(
                        .easeInOut(duration: 1.6)
                            .repeatForever(autoreverses: true),
                        value: isAnimating
                    )

                Image(systemName: symbolName)
                    .font(.footnote)
                    .symbolRenderingMode(.multicolor)
                    .foregroundStyle(.yellow.opacity(0.9), .orange.opacity(0.7), .white)
                    .scaleEffect(isAnimating ? 1.1 : 0.92)
                    .rotationEffect(.degrees(isAnimating ? 6 : -6))
                    .animation(
                        .easeInOut(duration: 1.3)
                            .repeatForever(autoreverses: true),
                        value: isAnimating
                    )
            }
            .frame(width: 28, height: 28)
        }
        .buttonStyle(.plain)
        .accessibilityLabel("AI Generated")
        .onAppear { isAnimating = true }
        .onDisappear { isAnimating = false }
        .alert("AI Generated Content", isPresented: $showDisclosure) {
            Button("OK", role: .cancel) {}
        } message: {
            Text(message)
        }
    }
}

#Preview {
    AIGeneratedBadge()
}
