//
//  AIGeneratedBadge.swift
//  swiftbible
//
//  Created by OpenAI.
//

import SwiftUI

/// Centralized attribution text for AI-generated devotionals. The model
/// identifier is sourced from the Daily Devotional row's `model` column
/// (set by the Edge Function), with a fallback for older rows.
enum AIAttribution {
    /// Used when a row has no `model` value (older rows or local cache misses).
    /// Should be kept roughly in sync with the Edge Function's DEVOTIONAL_MODEL.
    static let fallbackModel = "GPT-5.4"

    private static let disclaimer = """
        Large language models can make mistakes, produce inaccurate \
        information, or generate content that may not align with biblical \
        teaching. Always verify important information and consult trusted sources.
        """

    static func devotionalSingle(model: String?) -> String {
        "This devotional was generated by \(displayName(for: model)) via OpenAI from a single Bible verse. \(disclaimer)"
    }

    static func devotionalDual(model: String?) -> String {
        "This devotional was generated by \(displayName(for: model)) via OpenAI, weaving together verses from two thematically connected Bible books. \(disclaimer)"
    }

    static func devotionalHoliday(name: String, model: String?) -> String {
        "This devotional was generated by \(displayName(for: model)) in honor of \(name). \(disclaimer)"
    }

    static let styleEmpathy = """
        Empathy style — written to meet you where you are. \
        It opens by naming a real human struggle, weaves Scripture into that \
        moment, and closes with a prayer rather than a checklist.
        """

    static let styleTechnical = """
        Technical style — leans into the original Hebrew or Greek, historical \
        context, and a structured walk through what the verse actually says \
        before applying it to today.
        """

    static let styleNarrative = """
        Narrative style — drops you inside the biblical scene. Present tense, \
        sensory, observational. Stays close to what scripture actually supplies — \
        no invented dialogue, no guessed motivations.
        """

    static let stylePractical = """
        Practical style — one concrete action for today. Plain language, \
        honest about the cost. No "five ways to..." — just the one thing \
        the verse is asking of you.
        """

    /// Renders a stored model identifier (e.g. "gpt-5.4") in the human-readable
    /// form the UI uses (e.g. "GPT-5.4"). Falls back to `fallbackModel` when the
    /// stored value is nil or empty.
    private static func displayName(for raw: String?) -> String {
        guard let raw, !raw.isEmpty else { return fallbackModel }
        return raw.replacingOccurrences(
            of: "gpt-",
            with: "GPT-",
            options: [.caseInsensitive]
        )
    }
}

/// Reusable animated circular badge — a glassy disc with a rotating angular
/// gradient ring and a pulsing/wiggling SF Symbol at its center. Used for AI
/// attribution badges as well as custom and holiday devotional markers.
struct AnimatedBadgeCircle: View {
    var symbolName: String
    var primaryTint: Color
    var secondaryTint: Color
    var tertiaryTint: Color = .purple

    @State private var isAnimating = false

    var body: some View {
        ZStack {
            Circle()
                .fill(.ultraThinMaterial)
                .overlay(
                    Circle()
                        .stroke(.secondary.opacity(0.25), lineWidth: 1)
                )
                .overlay(
                    Circle()
                        .stroke(
                            AngularGradient(
                                colors: [
                                    primaryTint.opacity(0.8),
                                    secondaryTint.opacity(0.4),
                                    tertiaryTint.opacity(0.6),
                                    primaryTint.opacity(0.8)
                                ],
                                center: .center
                            ),
                            lineWidth: 1.4
                        )
                        .rotationEffect(.degrees(isAnimating ? 360 : 0))
                        .animation(
                            .linear(duration: 2.4)
                                .repeatForever(autoreverses: false),
                            value: isAnimating
                        )
                )
                .shadow(color: primaryTint.opacity(0.25), radius: isAnimating ? 4 : 0)
                .animation(
                    .easeInOut(duration: 1.6)
                        .repeatForever(autoreverses: true),
                    value: isAnimating
                )

            Image(systemName: symbolName)
                .font(.footnote)
                .symbolRenderingMode(.multicolor)
                .foregroundStyle(primaryTint.opacity(0.9), secondaryTint.opacity(0.7), .white)
                .scaleEffect(isAnimating ? 1.1 : 0.92)
                .rotationEffect(.degrees(isAnimating ? 6 : -6))
                .animation(
                    .easeInOut(duration: 1.3)
                        .repeatForever(autoreverses: true),
                    value: isAnimating
                )
        }
        .frame(width: 28, height: 28)
        .onAppear { isAnimating = true }
        .onDisappear { isAnimating = false }
    }
}

struct AIGeneratedBadge: View {
    var message: String = "This text was generated by Apple Intelligence."
    var symbolName: String = "sparkles"
    var primaryTint: Color = .yellow
    var secondaryTint: Color = .orange

    @State private var showDisclosure = false

    var body: some View {
        Button {
            showDisclosure = true
        } label: {
            AnimatedBadgeCircle(
                symbolName: symbolName,
                primaryTint: primaryTint,
                secondaryTint: secondaryTint
            )
        }
        .buttonStyle(.plain)
        .accessibilityLabel("AI Generated")
        .alert("AI Generated Content", isPresented: $showDisclosure) {
            Button("OK", role: .cancel) {}
        } message: {
            Text(message)
        }
    }
}

/// Per-holiday badge styling. Names must match `Holiday.name` literals
/// returned by `getHolidayInternal` in the daily-devotional Edge Function
/// (`supabase/functions/daily-devotional/index.ts`). Unknown names fall
/// back to a generic red+gold gift.
struct HolidayBadgePalette {
    let primary: Color
    let secondary: Color
    let tertiary: Color
    let symbol: String

    static let fallback = HolidayBadgePalette(
        primary: .brandRed,
        secondary: .brandRedDark,
        tertiary: .brandGold,
        symbol: "gift.fill"
    )

    // swiftlint:disable:next cyclomatic_complexity function_body_length
    static func palette(for name: String) -> HolidayBadgePalette {
        switch name {
        // ── Christmas cycle: red + green + gold ──
        case "Christmas Day":
            return .init(primary: .brandRed, secondary: .brandGreen, tertiary: .brandGold, symbol: "gift.fill")
        case "Christmas Eve":
            return .init(primary: .brandRed, secondary: .brandGreen, tertiary: .brandGoldLight, symbol: "moon.stars.fill")

        // ── Advent: violet + rose for Gaudete (3rd Sunday) ──
        case "First Sunday of Advent":
            return .init(primary: .purple, secondary: .brandDeepNavy, tertiary: .brandGold, symbol: "1.circle.fill")
        case "Second Sunday of Advent":
            return .init(primary: .purple, secondary: .brandDeepNavy, tertiary: .brandGold, symbol: "2.circle.fill")
        case "Third Sunday of Advent":
            return .init(primary: .pink, secondary: .purple, tertiary: .brandGold, symbol: "3.circle.fill")
        case "Fourth Sunday of Advent":
            return .init(primary: .purple, secondary: .brandDeepNavy, tertiary: .brandGold, symbol: "4.circle.fill")

        // ── Epiphany season ──
        case "Epiphany", "Epiphany Eve":
            return .init(primary: .brandGold, secondary: .brandCyan, tertiary: .white, symbol: "star.fill")
        case "Baptism of Jesus":
            return .init(primary: .brandCyan, secondary: .brandGoldLight, tertiary: .brandAccent, symbol: "drop.fill")
        case "Transfiguration":
            return .init(primary: .brandGoldLight, secondary: .brandGold, tertiary: .white, symbol: "sun.max.fill")

        // ── Lent ──
        case "Shrove Tuesday":
            return .init(primary: .brandGold, secondary: .purple, tertiary: .orange, symbol: "party.popper.fill")
        case "Ash Wednesday":
            return .init(primary: .gray, secondary: .purple, tertiary: .brandCoverDark, symbol: "circle.dashed")
        case "Laetare Sunday":
            return .init(primary: .pink, secondary: .brandGold, tertiary: .purple, symbol: "heart.fill")

        // ── Holy Week: somber, mourning ──
        case "Palm Sunday":
            return .init(primary: .brandPeridot, secondary: .brandGreen, tertiary: .brandGold, symbol: "leaf.fill")
        case "Holy Monday", "Spy Wednesday":
            return .init(primary: .purple, secondary: .brandDeepNavy, tertiary: .brandCoverDark, symbol: "moon.fill")
        case "Maundy Thursday":
            return .init(primary: .brandRed, secondary: .purple, tertiary: .brandGold, symbol: "cup.and.saucer.fill")
        case "Good Friday":
            return .init(primary: .brandDeepNavy, secondary: .brandRedDark, tertiary: .brandCoverDark, symbol: "moon.stars.fill")
        case "Holy Saturday":
            return .init(primary: .brandDeepNavy, secondary: .gray, tertiary: .brandCoverDark, symbol: "moon.fill")

        // ── Easter and after ──
        case "Easter Sunday":
            return .init(primary: .brandGoldLight, secondary: .brandCyan, tertiary: .brandGold, symbol: "sun.max.fill")
        case "Ascension Day":
            return .init(primary: .brandCyan, secondary: .brandGoldLight, tertiary: .white, symbol: "arrow.up.circle.fill")
        case "Pentecost":
            return .init(primary: .brandRed, secondary: .orange, tertiary: .brandGold, symbol: "flame.fill")
        case "Trinity Sunday":
            return .init(primary: .brandGold, secondary: .white, tertiary: .brandCyan, symbol: "triangle.fill")

        // ── Other Christian feasts ──
        case "Reformation Day":
            return .init(primary: .brandRed, secondary: .brandDeepNavy, tertiary: .brandGold, symbol: "seal.fill")
        case "All Saints' Day":
            return .init(primary: .brandGold, secondary: .white, tertiary: .brandGoldLight, symbol: "star.fill")
        case "Christ the King Sunday":
            return .init(primary: .brandGold, secondary: .brandRed, tertiary: .brandRedDark, symbol: "crown.fill")
        case "Michaelmas":
            return .init(primary: .brandRed, secondary: .brandGold, tertiary: .brandDeepNavy, symbol: "shield.fill")

        // ── New Year's ──
        case "New Year's Eve":
            return .init(primary: .brandGold, secondary: .brandDeepNavy, tertiary: .brandGoldLight, symbol: "party.popper.fill")
        case "New Year's Day":
            return .init(primary: .brandGoldLight, secondary: .brandGold, tertiary: .brandCyan, symbol: "party.popper.fill")

        // ── Family ──
        case "Mother's Day":
            return .init(primary: .pink, secondary: .brandGoldLight, tertiary: .purple, symbol: "heart.fill")
        case "Father's Day":
            return .init(primary: .blue, secondary: .brandGold, tertiary: .brandDeepNavy, symbol: "heart.fill")

        // ── Thanksgiving ──
        case "Thanksgiving":
            return .init(primary: .brandGold, secondary: .orange, tertiary: .brandCoverLight, symbol: "leaf.fill")

        // ── US patriotic: red + blue + white ──
        case "Independence Day", "Flag Day", "Patriot Day":
            return .init(primary: .brandRed, secondary: .blue, tertiary: .white, symbol: "flag.fill")
        case "Memorial Day", "Veterans Day":
            return .init(primary: .brandRed, secondary: .blue, tertiary: .white, symbol: "flag.fill")
        case "Labor Day":
            return .init(primary: .blue, secondary: .brandGold, tertiary: .white, symbol: "hammer.fill")
        case "Martin Luther King Jr. Day":
            return .init(primary: .blue, secondary: .brandGold, tertiary: .brandRed, symbol: "quote.bubble.fill")
        case "Presidents' Day":
            return .init(primary: .blue, secondary: .brandRed, tertiary: .white, symbol: "building.columns.fill")
        case "Election Day":
            return .init(primary: .blue, secondary: .brandRed, tertiary: .white, symbol: "checkmark.square.fill")
        case "Juneteenth":
            return .init(primary: .brandRed, secondary: .brandGreen, tertiary: .brandGold, symbol: "flag.fill")

        // ── Prayer days ──
        case "World Day of Prayer":
            return .init(primary: .brandGold, secondary: .brandCyan, tertiary: .white, symbol: "hand.raised.fill")
        case "National Day of Prayer":
            return .init(primary: .brandGold, secondary: .blue, tertiary: .white, symbol: "hand.raised.fill")

        // ── Cultural ──
        case "Valentine's Day":
            return .init(primary: .pink, secondary: .brandRed, tertiary: .brandRedDark, symbol: "heart.fill")
        case "St. Patrick's Day":
            return .init(primary: .brandGreen, secondary: .brandPeridot, tertiary: .brandGold, symbol: "leaf.fill")
        case "International Day of Peace":
            return .init(primary: .brandCyan, secondary: .white, tertiary: .brandPeridot, symbol: "peacesign")

        // ── Earth & seasons ──
        case "Earth Day":
            return .init(primary: .brandGreen, secondary: .brandPeridot, tertiary: .brandCyan, symbol: "globe.americas.fill")
        case "Spring Equinox":
            return .init(primary: .brandPeridot, secondary: .brandGreen, tertiary: .pink, symbol: "leaf.fill")
        case "Summer Solstice":
            return .init(primary: .brandGold, secondary: .orange, tertiary: .brandCyan, symbol: "sun.max.fill")
        case "Autumn Equinox":
            return .init(primary: .orange, secondary: .brandRed, tertiary: .brandGold, symbol: "leaf.fill")
        case "Winter Solstice":
            return .init(primary: .brandCyan, secondary: .brandDeepNavy, tertiary: .white, symbol: "snowflake")

        default:
            return .fallback
        }
    }
}

/// Small tinted pill indicating the prompting style ("track") that produced
/// an AI-generated devotional. Driven by the `track` column on the Daily
/// Devotional row (set by the Edge Function's TRACK_CYCLE).
struct DevotionalStyleChip: View {
    let track: String

    @State private var showInfo = false

    private var emoji: String? {
        switch track {
        case "empathy": return "💗"
        case "technical": return "🧠"
        case "narrative": return "🌅"
        case "practical": return "🛠️"
        default: return nil
        }
    }

    private var label: String? {
        switch track {
        case "empathy": return "Empathy"
        case "technical": return "Technical"
        case "narrative": return "Narrative"
        case "practical": return "Practical"
        default: return nil
        }
    }

    private var tint: Color {
        switch track {
        case "empathy": return .pink
        case "technical": return .indigo
        case "narrative": return .orange
        case "practical": return .green
        default: return .secondary
        }
    }

    private var infoText: String {
        switch track {
        case "empathy": return AIAttribution.styleEmpathy
        case "technical": return AIAttribution.styleTechnical
        case "narrative": return AIAttribution.styleNarrative
        case "practical": return AIAttribution.stylePractical
        default: return ""
        }
    }

    var body: some View {
        if let emoji, let label {
            Button { showInfo = true } label: {
                HStack(spacing: 4) {
                    Text(emoji)
                    Text(label)
                        .fontWeight(.medium)
                }
                .font(.caption)
                .padding(.horizontal, 8)
                .padding(.vertical, 3)
                .background(tint.opacity(0.15), in: Capsule())
                .overlay(Capsule().stroke(tint.opacity(0.35), lineWidth: 0.5))
                .foregroundStyle(tint)
            }
            .buttonStyle(.plain)
            .accessibilityLabel("\(label) style. Tap to learn more.")
            .alert("\(label) style", isPresented: $showInfo) {
                Button("OK", role: .cancel) {}
            } message: {
                Text(infoText)
            }
        }
    }
}

#Preview {
    AIGeneratedBadge()
}
