//
//  AIGeneratedBadge.swift
//  swiftbible
//
//  Created by OpenAI.
//

import SwiftUI

/// Centralized attribution text for AI-generated devotionals. The model
/// identifier is sourced from the Daily Devotional row's `model` column
/// (set by the Edge Function), with a fallback for older rows.
enum AIAttribution {
    /// Used when a row has no `model` value (older rows or local cache misses).
    /// Should be kept roughly in sync with the Edge Function's DEVOTIONAL_MODEL.
    static let fallbackModel = "GPT-5.5"

    private static let disclaimer = """
        Large language models can make mistakes, produce inaccurate \
        information, or generate content that may not align with biblical \
        teaching. Always verify important information and consult trusted sources.
        """

    static func devotionalSingle(model: String?) -> String {
        "This devotional was generated by \(displayName(for: model)) via OpenAI from a single Bible verse. \(disclaimer)"
    }

    static func devotionalDual(model: String?) -> String {
        "This devotional was generated by \(displayName(for: model)) via OpenAI, weaving together verses from two thematically connected Bible books. \(disclaimer)"
    }

    static func devotionalHoliday(name: String, model: String?) -> String {
        "This devotional was generated by \(displayName(for: model)) in honor of \(name). \(disclaimer)"
    }

    /// Renders a stored model identifier (e.g. "gpt-5.5") in the human-readable
    /// form the UI uses (e.g. "GPT-5.5"). Falls back to `fallbackModel` when the
    /// stored value is nil or empty.
    private static func displayName(for raw: String?) -> String {
        guard let raw, !raw.isEmpty else { return fallbackModel }
        return raw.replacingOccurrences(
            of: "gpt-",
            with: "GPT-",
            options: [.caseInsensitive]
        )
    }
}

struct AIGeneratedBadge: View {
    var message: String = "This text was generated by Apple Intelligence."
    var symbolName: String = "sparkles"
    var primaryTint: Color = .yellow
    var secondaryTint: Color = .orange

    @State private var showDisclosure = false
    @State private var isAnimating = false

    var body: some View {
        Button {
            showDisclosure = true
        } label: {
            ZStack {
                Circle()
                    .fill(.ultraThinMaterial)
                    .overlay(
                        Circle()
                            .stroke(.secondary.opacity(0.25), lineWidth: 1)
                    )
                    .overlay(
                        Circle()
                            .stroke(
                                AngularGradient(
                                    colors: [
                                        primaryTint.opacity(0.8),
                                        secondaryTint.opacity(0.4),
                                        .purple.opacity(0.6),
                                        primaryTint.opacity(0.8)
                                    ],
                                    center: .center
                                ),
                                lineWidth: 1.4
                            )
                            .rotationEffect(.degrees(isAnimating ? 360 : 0))
                            .animation(
                                .linear(duration: 2.4)
                                    .repeatForever(autoreverses: false),
                                value: isAnimating
                            )
                    )
                    .shadow(color: primaryTint.opacity(0.25), radius: isAnimating ? 4 : 0)
                    .animation(
                        .easeInOut(duration: 1.6)
                            .repeatForever(autoreverses: true),
                        value: isAnimating
                    )

                Image(systemName: symbolName)
                    .font(.footnote)
                    .symbolRenderingMode(.multicolor)
                    .foregroundStyle(primaryTint.opacity(0.9), secondaryTint.opacity(0.7), .white)
                    .scaleEffect(isAnimating ? 1.1 : 0.92)
                    .rotationEffect(.degrees(isAnimating ? 6 : -6))
                    .animation(
                        .easeInOut(duration: 1.3)
                            .repeatForever(autoreverses: true),
                        value: isAnimating
                    )
            }
            .frame(width: 28, height: 28)
        }
        .buttonStyle(.plain)
        .accessibilityLabel("AI Generated")
        .onAppear { isAnimating = true }
        .onDisappear { isAnimating = false }
        .alert("AI Generated Content", isPresented: $showDisclosure) {
            Button("OK", role: .cancel) {}
        } message: {
            Text(message)
        }
    }
}

#Preview {
    AIGeneratedBadge()
}
