CREATE TABLE IF NOT EXISTS "public"."Verse Info" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT now() NOT NULL,
    "version" text NOT NULL,
    "book" text NOT NULL,
    "chapter" integer NOT NULL,
    "starting_verse" integer NOT NULL,
    "info" text DEFAULT ''::text
);

ALTER TABLE "public"."Verse Info" OWNER TO "postgres";

ALTER TABLE "public"."Verse Info" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."Verse Info_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY "public"."Verse Info"
    ADD CONSTRAINT "Verse Info_pkey" PRIMARY KEY ("id");

ALTER TABLE ONLY "public"."Verse Info"
    ADD CONSTRAINT "one_info_per_verse" UNIQUE ("version", "book", "chapter", "starting_verse");

ALTER TABLE "public"."Verse Info" ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Enable insert for authenticated users only" ON "public"."Verse Info" FOR INSERT TO "anon" WITH CHECK (true);

CREATE POLICY "Enable read access for all users" ON "public"."Verse Info" FOR SELECT USING (true);

GRANT ALL ON TABLE "public"."Verse Info" TO "anon";
GRANT ALL ON TABLE "public"."Verse Info" TO "authenticated";
GRANT ALL ON TABLE "public"."Verse Info" TO "service_role";
GRANT ALL ON SEQUENCE "public"."Verse Info_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."Verse Info_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."Verse Info_id_seq" TO "service_role";
