-- 20250713_create_verse_info.sql
-- Creates a row-level-secured table that stores one commentary per verse.

-- 1️⃣  Table + constraints
create table public.verse_info (
  id               bigint generated by default as identity primary key,
  created_at       timestamptz not null default now(),
  version          text        not null,
  book             text        not null,
  chapter          int         not null,
  starting_verse   int         not null,
  info             text        not null default '',
  constraint verse_info_one_per_verse
    unique (version, book, chapter, starting_verse)
);

-- 2️⃣  Row-level security
alter table public.verse_info enable row level security;

-- 3️⃣  Policies
-- Anyone (anon, authenticated, service_role) can read.
create policy "Anyone can read verse_info"
  on public.verse_info
  for select
  using (true);

-- Only signed-in users (authenticated) may insert.
create policy "Authenticated can insert verse_info"
  on public.verse_info
  for insert
  to authenticated
  with check (true);   -- no row predicate; all inserts allowed

-- (Optional) If you ever want updates/deletes, add policies here.

-- 4️⃣  Grants
-- Table privileges
grant select          on public.verse_info      to anon;
grant select, insert  on public.verse_info      to authenticated;
grant all             on public.verse_info      to service_role;

-- Sequence privileges (needed because we used `generated … identity`)
grant usage, select   on sequence public.verse_info_id_seq to anon;
grant usage, select   on sequence public.verse_info_id_seq to authenticated;
grant all             on sequence public.verse_info_id_seq to service_role;
